'use client';
/* eslint-disable next/no-img-element, jsx-a11y/anchor-has-content, jsx-a11y/control-has-associated-label */
import Link from 'next/link';
import { useRef, useState } from 'react';
import { AlertTriangle, Archive, ArrowLeft, Check, Download, ExternalLink, Eye, FileCheck, Maximize2, RefreshCw, RotateCcw, RotateCw, ScanText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { hasPermission } from '@/lib/security/permissions';

type Workspace = {
  document: { id: string; internalNumber: string; title: string; category: string; originalFilename: string; mimeType: string; sizeBytes: number; referenceNumber: string | null; documentDate: string | null; description: string | null; relatedModule: string | null; relatedRecordId: string | null; tagsJson: string | null; notes: string | null; rawOcrText: string | null; ocrStatus: string; verificationStatus: string; uploadedAt: string; uploadedByName: string; archivedAt: string | null };
  jobs: Array<{ id: string; provider: string; providerMode: string; status: string; confidenceBasisPoints: number | null; attempts: number; errorMessage: string | null; createdAt: string; completedAt: string | null }>;
  links: Array<{ id: string; entityType: string; entityId: string; relationship: string }>;
  receipt: { receipt: { id: string; internalNumber: string; totalMinor: string; currency: string; receiptNumber: string | null; reviewedAt: string }; reviewerName: string; supplierName: string | null } | null;
  audit: Array<{ id: string; action: string; occurredAt: string }>;
};
const pretty = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (char) => char.toUpperCase());
export function DocumentDetail({ workspace, permissions }: { workspace: Workspace; permissions: readonly string[] }) {
  const { document } = workspace; const previewRef = useRef<HTMLDivElement>(null); const [rotation, setRotation] = useState(0); const [zoom, setZoom] = useState(1); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const runOcr = async () => { setBusy('ocr'); setError(''); const response = await fetch(`/api/documents/${document.id}/ocr`, { method: 'POST' }); const body = await response.json() as { error?: string }; if (!response.ok) { setBusy(''); setError(body.error ?? 'OCR failed.'); } else window.location.assign(`/documents/${document.id}/review`); };
  const archive = async () => { if (!window.confirm('Archive this document? The original will remain in private storage and its audit history will be preserved.')) return; setBusy('archive'); const response = await fetch(`/api/documents/${document.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'archive' }) }); if (response.ok) window.location.assign('/documents'); else { const body = await response.json() as { error?: string }; setBusy(''); setError(body.error ?? 'Document could not be archived.'); } };
  return <main className="page-content document-detail-page">
    <header className="document-detail-head"><div><Link href="/documents"><ArrowLeft />Back to documents</Link><p className="eyebrow">{document.internalNumber}</p><h1>{document.title}</h1><p>{document.originalFilename} · {(document.sizeBytes / 1024 / 1024).toFixed(2)} MB</p></div><div className="heading-actions">{hasPermission(permissions, 'documents.download') ? <Button variant="outline" render={<a href={`/api/documents/${document.id}/file?download=1`} />}><Download />Download original</Button> : null}{workspace.receipt ? <Button render={<Link href={`/documents/${document.id}/receipt`} />}><FileCheck />Digitized receipt</Button> : hasPermission(permissions, 'documents.ocr') ? <Button onClick={runOcr} disabled={Boolean(busy)}><ScanText />{busy === 'ocr' ? 'Processing…' : document.ocrStatus === 'failed' ? 'Retry OCR' : 'Process with OCR'}</Button> : null}</div></header>
    {error ? <div className="form-error" role="alert"><AlertTriangle />{error}</div> : null}
    <div className="document-detail-grid"><section className="panel document-detail-preview"><header><div><p className="eyebrow">Secured original</p><h2>Document preview</h2></div><span className={`document-status ${document.verificationStatus === 'verified' ? 'success' : 'warning'}`}>{pretty(document.verificationStatus)}</span></header>{document.mimeType === 'application/x-star-africa-manual' ? <div className="missing-original"><AlertTriangle /><h3>No original attached</h3><p>This receipt was entered manually. Upload the source and link it when evidence becomes available.</p><Button render={<Link href="/documents/upload" />}>Upload source document</Button></div> : <><div className="preview-toolbar"><Button variant="outline" size="sm" onClick={() => setZoom((v) => Math.min(v + .25, 2.5))}>Zoom +</Button><Button variant="outline" size="sm" onClick={() => setZoom(1)}>Fit</Button><Button variant="outline" size="icon-sm" aria-label="Rotate left" onClick={() => setRotation((v) => v - 90)}><RotateCcw /></Button><Button variant="outline" size="icon-sm" aria-label="Rotate right" onClick={() => setRotation((v) => v + 90)}><RotateCw /></Button><Button variant="outline" size="icon-sm" aria-label="Fullscreen" onClick={() => previewRef.current?.requestFullscreen()}><Maximize2 /></Button></div><div ref={previewRef} className="detail-preview-stage">{document.mimeType === 'application/pdf' ? <iframe title="PDF document preview" src={`/api/documents/${document.id}/file`} /> : <img alt={document.title} src={`/api/documents/${document.id}/file`} style={{ transform: `rotate(${rotation}deg) scale(${zoom})` }} />}</div></>}</section>
      <aside className="document-detail-aside"><section className="panel metadata-card"><header><p className="eyebrow">Document metadata</p><h2>Record details</h2></header><dl><div><dt>Internal ID</dt><dd>{document.internalNumber}</dd></div><div><dt>Category</dt><dd>{document.category}</dd></div><div><dt>Reference</dt><dd>{document.referenceNumber || '—'}</dd></div><div><dt>Document date</dt><dd>{document.documentDate ? new Date(document.documentDate).toLocaleDateString('en-UG', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}</dd></div><div><dt>Uploaded by</dt><dd>{document.uploadedByName}</dd></div><div><dt>Uploaded</dt><dd>{new Date(document.uploadedAt).toLocaleString('en-UG')}</dd></div><div><dt>OCR status</dt><dd><span className={`document-status ${document.ocrStatus === 'confirmed' ? 'success' : document.ocrStatus === 'failed' ? 'danger' : 'warning'}`}>{pretty(document.ocrStatus)}</span></dd></div></dl>{document.description ? <p className="document-description">{document.description}</p> : null}</section>
      <section className="panel linked-records"><header><p className="eyebrow">Relationships</p><h2>Linked records</h2></header>{workspace.links.length ? workspace.links.map((link) => <div key={link.id}><span><ExternalLink /></span><p><strong>{link.entityId}</strong><small>{link.entityType} · {pretty(link.relationship)}</small></p></div>) : <p className="muted-block">This document has not been linked to a business record.</p>}{workspace.receipt ? <div><span><Check /></span><p><strong>{workspace.receipt.receipt.internalNumber}</strong><small>Verified by {workspace.receipt.reviewerName}</small></p></div> : null}</section></aside></div>
    <div className="document-lower-grid"><section className="panel document-history"><header><p className="eyebrow">Processing history</p><h2>OCR attempts</h2></header>{workspace.jobs.length ? workspace.jobs.map((job) => <article key={job.id}><span className={`history-icon ${job.status}`}><RefreshCw /></span><div><strong>Attempt {job.attempts} · {job.provider}</strong><p>{pretty(job.status)}{job.confidenceBasisPoints ? ` · ${Math.round(job.confidenceBasisPoints / 100)}% confidence` : ''}</p><small>{new Date(job.createdAt).toLocaleString('en-UG')}{job.errorMessage ? ` · ${job.errorMessage}` : ''}</small></div></article>) : <p className="muted-block">No OCR attempts have been made.</p>}</section><section className="panel document-history"><header><p className="eyebrow">Audit trail</p><h2>Document activity</h2></header>{workspace.audit.map((event) => <article key={event.id}><span className="history-icon"><Eye /></span><div><strong>{pretty(event.action.replace('document.', ''))}</strong><small>{new Date(event.occurredAt).toLocaleString('en-UG')}</small></div></article>)}</section></div>
    {document.rawOcrText ? <details className="panel raw-ocr"><summary>View raw OCR text</summary><pre>{document.rawOcrText}</pre></details> : null}
    {hasPermission(permissions, 'documents.delete') ? <div className="archive-row"><Button variant="destructive" disabled={Boolean(busy)} onClick={archive}><Archive />{busy === 'archive' ? 'Archiving…' : 'Archive document'}</Button><span>Financial evidence is archived, not permanently deleted.</span></div> : null}
  </main>;
}
