'use client';
/* eslint-disable next/no-img-element, jsx-a11y/label-has-associated-control */
import Link from 'next/link';
import { useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowLeft, Check, Download, Maximize2, Plus, RefreshCw, RotateCcw, RotateCw, Save, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { Textarea } from '@/components/ui/textarea';
import { emptyReceiptFields, type OcrExtraction, type ReceiptFields, type ReceiptLine } from '@/lib/documents/types';

type DocumentInfo = { id: string; internalNumber: string; title: string; category: string; mimeType: string; originalFilename: string; ocrStatus: string };
type Options = { projects: Array<{ id: string; code: string; name: string }>; suppliers: Array<{ id: string; code: string; name: string }> };
const fieldGroups: Array<{ title: string; fields: Array<[keyof ReceiptFields, string, string?]> }> = [
  { title: 'Supplier & reference', fields: [['supplierName', 'Supplier / merchant'], ['supplierTin', 'Supplier TIN'], ['businessAddress', 'Business address'], ['telephone', 'Telephone'], ['receiptNumber', 'Source receipt no.'], ['invoiceNumber', 'Invoice no.']] },
  { title: 'Transaction', fields: [['date', 'Date', 'date'], ['time', 'Time', 'time'], ['currency', 'Currency'], ['paymentMethod', 'Payment method'], ['transactionReference', 'Transaction reference'], ['cashier', 'Cashier'], ['customerName', 'Customer name'], ['projectReference', 'Project / reference']] },
  { title: 'Totals', fields: [['subtotal', 'Subtotal', 'number'], ['discount', 'Discount', 'number'], ['vatAmount', 'VAT amount', 'number'], ['vatRate', 'VAT rate %', 'number'], ['otherTax', 'Other tax', 'number'], ['total', 'Total amount', 'number'], ['amountPaid', 'Amount paid', 'number'], ['change', 'Change', 'number']] },
];

function confidenceClass(value = 0) { return value >= 85 ? 'high' : value >= 60 ? 'medium' : 'low'; }
function blankExtraction(category: string): OcrExtraction { return { documentType: category === 'Supplier Invoice' ? 'Supplier Invoice' : 'Receipt', fields: { ...emptyReceiptFields }, lineItems: [], fieldConfidence: {}, overallConfidence: 0, warnings: ['Values entered manually require human verification.'], rawText: '' }; }

export function OcrReview({ document, initialExtraction, options }: { document: DocumentInfo; initialExtraction: OcrExtraction | null; options: Options }) {
  const extraction = initialExtraction ?? blankExtraction(document.category);
  const [fields, setFields] = useState<ReceiptFields>({ ...emptyReceiptFields, ...extraction.fields });
  const [items, setItems] = useState<ReceiptLine[]>(extraction.lineItems ?? []);
  const [rotation, setRotation] = useState(0); const [zoom, setZoom] = useState(1); const previewRef = useRef<HTMLDivElement>(null);
  const [linkType, setLinkType] = useState(''); const [linkId, setLinkId] = useState(''); const [expenseCategory, setExpenseCategory] = useState('Materials'); const [expenseDescription, setExpenseDescription] = useState('');
  const [supplierId, setSupplierId] = useState(''); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [duplicate, setDuplicate] = useState<{ id: string; internalNumber: string; documentId: string } | null>(null);
  const supplierMatch = useMemo(() => options.suppliers.find((supplier) => fields.supplierName && supplier.name.toLowerCase().includes(fields.supplierName.toLowerCase().replace(/\s+demo$/i, ''))) ?? options.suppliers.find((supplier) => fields.supplierName && fields.supplierName.toLowerCase().includes(supplier.name.toLowerCase().replace(/\s+demo$/i, ''))), [fields.supplierName, options.suppliers]);
  const lineSum = items.reduce((sum, item) => sum + (Number(item.lineTotal) || 0), 0); const subtotal = Number(fields.subtotal) || 0; const total = Number(fields.total) || 0; const calculated = subtotal - (Number(fields.discount) || 0) + (Number(fields.vatAmount) || 0) + (Number(fields.otherTax) || 0);
  const totalWarning = (items.length > 0 && Math.abs(lineSum - subtotal) > .01) || (total > 0 && Math.abs(calculated - total) > .01);
  const updateField = (field: keyof ReceiptFields, value: string) => setFields((current) => ({ ...current, [field]: value }));
  const currentExtraction = (): OcrExtraction => ({ ...extraction, fields, lineItems: items, warnings: [...new Set([...extraction.warnings, ...(totalWarning ? ['Receipt totals require review.'] : [])])] });
  const saveDraft = async () => { setBusy('draft'); setError(''); const response = await fetch(`/api/documents/${document.id}/review`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(currentExtraction()) }); const body = await response.json() as { error?: string }; setBusy(''); if (!response.ok) setError(body.error ?? 'Draft could not be saved.'); };
  const retry = async () => { setBusy('ocr'); setError(''); const response = await fetch(`/api/documents/${document.id}/ocr`, { method: 'POST' }); const body = await response.json() as { error?: string }; if (!response.ok) { setBusy(''); setError(body.error ?? 'OCR retry failed.'); } else window.location.reload(); };
  const confirm = async (saveAnyway = false) => { setBusy('confirm'); setError(''); const response = await fetch(`/api/documents/${document.id}/confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fields, lineItems: items, supplierId: supplierId || undefined, link: linkType ? { type: linkType, id: linkId, category: expenseCategory, description: expenseDescription } : undefined, saveAnyway }) }); const body = await response.json() as { error?: string; duplicate?: { id: string; internalNumber: string; documentId: string } }; setBusy(''); if (response.status === 409 && body.duplicate) { setDuplicate(body.duplicate); setError(body.error ?? 'Possible duplicate.'); return; } if (!response.ok) { setError(body.error ?? 'Receipt could not be confirmed.'); return; } window.location.assign(`/documents/${document.id}/receipt`); };
  return <main className="page-content ocr-review-page">
    <header className="ocr-review-head"><div><Link href={`/documents/${document.id}`}><ArrowLeft />Back to document</Link><p className="eyebrow">Human verification required</p><h1>Receipt review</h1><p>Compare every value with the secured original before confirming.</p></div><div><span>{document.internalNumber}</span><strong>{document.title}</strong></div></header>
    <section className="document-workflow compact" aria-label="OCR workflow">{['Upload', 'Process', 'Extract', 'Review', 'Confirm'].map((step, index) => <div className={index < 3 ? 'done' : index === 3 ? 'active' : ''} key={step}><span>{index < 3 ? <Check /> : index + 1}</span><strong>{step}</strong></div>)}</section>
    <div className="ocr-provider-banner"><span className="document-status warning">Development OCR provider</span><p>Production OCR is not configured. Extracted suggestions must be checked against the original.</p><Button variant="outline" size="sm" disabled={Boolean(busy)} onClick={retry}><RefreshCw />Retry OCR</Button></div>
    {extraction.warnings.length ? <div className="ocr-warning-list">{extraction.warnings.map((warning) => <p key={warning}><AlertTriangle />{warning}</p>)}</div> : null}
    <div className="ocr-split-layout">
      <section className="panel ocr-original"><header><div><p className="eyebrow">Original document</p><h2>{document.originalFilename}</h2></div>{document.mimeType !== 'application/x-star-africa-manual' ? <a href={`/api/documents/${document.id}/file?download=1`}><Download />Original</a> : null}</header>{document.mimeType === 'application/x-star-africa-manual' ? <div className="missing-original"><AlertTriangle /><h3>No original attached</h3><p>Enter values carefully. This record will remain visibly flagged as manual evidence.</p></div> : <><div className="preview-toolbar"><Button variant="outline" size="sm" onClick={() => setZoom((v) => Math.min(v + .25, 2.5))}>Zoom +</Button><Button variant="outline" size="sm" onClick={() => setZoom(1)}>Fit</Button><Button variant="outline" size="icon-sm" aria-label="Rotate left" onClick={() => setRotation((v) => v - 90)}><RotateCcw /></Button><Button variant="outline" size="icon-sm" aria-label="Rotate right" onClick={() => setRotation((v) => v + 90)}><RotateCw /></Button><Button variant="outline" size="icon-sm" aria-label="Fullscreen" onClick={() => previewRef.current?.requestFullscreen()}><Maximize2 /></Button></div><div ref={previewRef} className="ocr-preview-stage">{document.mimeType === 'application/pdf' ? <iframe title="Original PDF" src={`/api/documents/${document.id}/file`} /> : <img alt="Original receipt" src={`/api/documents/${document.id}/file`} style={{ transform: `rotate(${rotation}deg) scale(${zoom})` }} />}</div></>}</section>
      <section className="panel ocr-fields"><header><div><p className="eyebrow">Extracted information</p><h2>Review &amp; correct</h2></div><div className={`confidence-chip ${confidenceClass(extraction.overallConfidence)}`}><strong>{extraction.overallConfidence}%</strong><span>overall confidence</span></div></header>{fieldGroups.map((group) => <fieldset key={group.title}><legend>{group.title}</legend><div className="ocr-field-grid">{group.fields.map(([field, label, type]) => <label key={field} className={field === 'businessAddress' ? 'wide' : ''}><span>{label}<i className={`confidence-dot ${confidenceClass(extraction.fieldConfidence[field])}`} title={`${extraction.fieldConfidence[field] ?? 0}% OCR confidence`} /></span><Input type={type ?? 'text'} step={type === 'number' ? '0.01' : undefined} value={fields[field]} onChange={(e) => updateField(field, e.target.value)} /></label>)}</div></fieldset>)}<fieldset><legend>VAT &amp; notes</legend><div className="ocr-field-grid"><label><span>VAT treatment</span><NativeSelect value={fields.vatTreatment} onChange={(e) => updateField('vatTreatment', e.target.value)}><option value="unknown">Unknown</option><option value="inclusive">VAT inclusive</option><option value="exclusive">VAT exclusive</option><option value="none">No VAT detected</option></NativeSelect></label><label className="wide"><span>Notes</span><Textarea value={fields.notes} onChange={(e) => updateField('notes', e.target.value)} /></label></div></fieldset></section>
    </div>
    <section className="panel review-lines"><header><div><p className="eyebrow">Line items</p><h2>Items on the receipt</h2><p>Add missing lines and correct OCR mistakes.</p></div><Button variant="outline" onClick={() => setItems([...items, { description: '', quantity: '1', unit: '', unitPrice: '0', tax: '0', lineTotal: '0' }])}><Plus />Add item</Button></header><div className="table-scroll"><table><thead><tr><th>Description</th><th>Quantity</th><th>Unit</th><th>Unit price</th><th>Tax</th><th>Line total</th><th><span className="sr-only">Remove</span></th></tr></thead><tbody>{items.length ? items.map((item, index) => <tr key={item.id ?? index}><td><Input aria-label={`Item ${index + 1} description`} value={item.description} onChange={(e) => setItems(items.map((line, i) => i === index ? { ...line, description: e.target.value } : line))} /></td>{(['quantity', 'unit', 'unitPrice', 'tax', 'lineTotal'] as const).map((key) => <td key={key}><Input aria-label={`Item ${index + 1} ${key}`} type={key === 'unit' ? 'text' : 'number'} step="0.01" value={item[key]} onChange={(e) => setItems(items.map((line, i) => i === index ? { ...line, [key]: e.target.value } : line))} /></td>)}<td><Button variant="ghost" size="icon-sm" aria-label={`Remove item ${index + 1}`} onClick={() => setItems(items.filter((_, i) => i !== index))}><Trash2 /></Button></td></tr>) : <tr><td colSpan={7}><div className="line-empty">No line items were detected. Add them manually when they are visible on the original.</div></td></tr>}</tbody></table></div><footer><span>Line total sum <strong>{fields.currency} {lineSum.toLocaleString('en-UG', { minimumFractionDigits: 2 })}</strong></span><span>Receipt subtotal <strong>{fields.currency} {subtotal.toLocaleString('en-UG', { minimumFractionDigits: 2 })}</strong></span></footer>{totalWarning ? <div className="inline-warning"><AlertTriangle /><span><strong>Receipt totals require review.</strong>Line items, subtotal, tax, and total do not reconcile. Values were not changed automatically.</span></div> : null}</section>
    <section className="panel receipt-link-panel"><header><p className="eyebrow">Business context</p><h2>What is this receipt for?</h2><p>Linking is optional. A project expense is created as a draft only after confirmation.</p></header>{supplierMatch ? <div className="supplier-match"><span><Check /></span><div><strong>Possible supplier match</strong><p>{supplierMatch.name} · {supplierMatch.code}</p></div><Button variant={supplierId === supplierMatch.id ? 'secondary' : 'outline'} onClick={() => setSupplierId(supplierMatch.id)}>{supplierId === supplierMatch.id ? 'Supplier selected' : 'Use supplier'}</Button></div> : null}<div className="document-form-grid"><label><span>Link type</span><NativeSelect value={linkType} onChange={(e) => { setLinkType(e.target.value); setLinkId(''); }}><option value="">Document only</option><option>Project</option><option>Project Expense</option><option>Supplier</option><option>Payment</option><option>Invoice</option><option>Bid Expense</option><option>General Company Expense</option></NativeSelect></label><label><span>Related record</span>{linkType === 'Project' || linkType === 'Project Expense' ? <NativeSelect value={linkId} onChange={(e) => setLinkId(e.target.value)}><option value="">Select project</option>{options.projects.map((project) => <option value={project.id} key={project.id}>{project.code} — {project.name}</option>)}</NativeSelect> : <Input value={linkId} onChange={(e) => setLinkId(e.target.value)} placeholder="Record ID or reference" />}</label>{linkType === 'Project' || linkType === 'Project Expense' ? <><label><span>Expense category</span><NativeSelect value={expenseCategory} onChange={(e) => setExpenseCategory(e.target.value)}><option>Materials</option><option>Transport</option><option>Labour</option><option>Equipment</option><option>Other</option></NativeSelect></label><label><span>Expense description</span><Input value={expenseDescription} onChange={(e) => setExpenseDescription(e.target.value)} placeholder="e.g. Cement purchase" /></label></> : null}</div></section>
    {error ? <div className="form-error review-error" role="alert"><AlertTriangle />{error}{duplicate ? <span><Link href={`/documents/${duplicate.documentId}`}>View existing {duplicate.internalNumber}</Link><button onClick={() => confirm(true)}>Save anyway — authorized</button></span> : null}</div> : null}
    <footer className="review-actions"><Button variant="outline" render={<Link href={`/documents/${document.id}`} />}>Cancel</Button><Button variant="outline" disabled={Boolean(busy)} onClick={saveDraft}><Save />{busy === 'draft' ? 'Saving…' : 'Save draft'}</Button><Button disabled={Boolean(busy) || !fields.supplierName || !fields.date || !fields.total} onClick={() => confirm()}><Check />{busy === 'confirm' ? 'Confirming…' : 'Confirm receipt'}</Button></footer>
  </main>;
}
