'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, BriefcaseBusiness, CalendarClock, Check, CheckCircle2, ClipboardCheck, Clock3, Download, Eye, FileCheck2, FileText, Landmark, MessageSquareText, MoreHorizontal, ReceiptText, ShieldCheck, Star } from 'lucide-react';
import { Button, buttonVariants } from '@/components/ui/button';
import { hasPermission } from '@/lib/security/permissions';
import { deadlineState, submissionReadiness } from '@/lib/bids/domain';
import { activities, formatMoney, labelStage, pricingLines, requirements, type DemoBid } from '@/lib/bids/demo-data';

const tabs=['Overview','Qualification','Requirements','Pricing / BOQ','Documents','Team & tasks','Expenses','Bid security','Approvals','Clarifications','Submission','Result','Activity'] as const;

export function BidWorkspace({bid,permissions,currentUser}:{bid:DemoBid;permissions:string[];currentUser:string}) {
  const [tab,setTab]=useState<(typeof tabs)[number]>('Overview'); const [message,setMessage]=useState(''); const [working,setWorking]=useState(false);
  const deadline=deadlineState(new Date(bid.deadline),new Date('2026-09-02T12:00:00+03:00')); const canEdit=hasPermission(permissions,'bids.edit'); const canApprove=hasPermission(permissions,'bids.approve'); const canSubmit=hasPermission(permissions,'bids.submit');
  const readiness=useMemo(()=>submissionReadiness({mandatoryRequirementsComplete:false,requiredDocumentsPresent:true,documentsValid:true,pricingApproved:true,technicalApproved:true,securityValid:true,finalApprovalComplete:false,deadline:new Date(bid.deadline)},new Date('2026-09-02T12:00:00+03:00')),[bid.deadline]);
  async function action(type:string,payload:Record<string,unknown>={}){setWorking(true);setMessage('');const response=await fetch(`/api/bids/${bid.id}/actions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type,...payload})});const result=await response.json() as {message?:string;error?:string};setMessage(response.ok?(result.message??'Action recorded.'):(result.error??'Action failed.'));setWorking(false);}
  return <div className="page-content bid-workspace-page">
    <Link className="back-link" href="/bids"><ArrowLeft/> All opportunities</Link>
    <header className="bid-detail-head"><div className="bid-title-block"><div><span className={`bid-status status-${bid.stage}`}>{labelStage(bid.stage)}</span>{bid.watched?<span className="watch-chip"><Star/> Watched</span>:null}</div><p>{bid.reference}</p><h1>{bid.title}</h1><span>{bid.organization} · {bid.category} · {bid.location}</span></div><div className="bid-head-metrics"><div><span>Submission deadline</span><strong>{new Date(bid.deadline).toLocaleString('en-UG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</strong><em className={`deadline-${deadline.tone}`}>{deadline.label}</em></div><div><span>Estimated value</span><strong>{formatMoney(bid.valueMinor,bid.currency)}</strong><em>{bid.currency}</em></div><div><span>Bid owner</span><strong>{bid.owner}</strong><em>{bid.priority} priority</em></div></div><div className="bid-head-actions"><Button variant="outline" onClick={()=>window.print()}><Download/> Export brief</Button>{canEdit?<Link className={buttonVariants({variant:'outline'})} href={`/bids/${bid.id}?edit=1`}>Edit</Link>:null}<Button variant="outline" disabled title="Additional actions are available within the relevant workspace tab"><MoreHorizontal/></Button></div></header>
    {message?<output className="action-message">{message}</output>:null}
    <nav className="workspace-tabs" aria-label="Bid workspace tabs">{tabs.map((item)=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    <div className="workspace-content">
      {tab==='Overview'?<Overview bid={bid} deadline={deadline}/>:null}
      {tab==='Qualification'?<Qualification bid={bid} canApprove={canApprove} working={working} action={action}/>:null}
      {tab==='Requirements'?<Requirements/>:null}
      {tab==='Pricing / BOQ'?<Pricing canEdit={hasPermission(permissions,'bids.pricing.edit')}/>:null}
      {tab==='Documents'?<Documents canUpload={hasPermission(permissions,'bids.documents.upload')}/>:null}
      {tab==='Team & tasks'?<TeamTasks canManage={hasPermission(permissions,'bids.team.manage')}/>:null}
      {tab==='Expenses'?<Expenses canCreate={hasPermission(permissions,'bids.expenses.create')} canApprove={hasPermission(permissions,'bids.expenses.approve')}/>:null}
      {tab==='Bid security'?<Security canManage={hasPermission(permissions,'bids.security.manage')}/>:null}
      {tab==='Approvals'?<Approvals canApprove={canApprove} working={working} action={action}/>:null}
      {tab==='Clarifications'?<Clarifications/>:null}
      {tab==='Submission'?<Submission readiness={readiness} canSubmit={canSubmit} working={working} action={action}/>:null}
      {tab==='Result'?<Result bid={bid} canAward={hasPermission(permissions,'bids.award')} working={working} action={action}/>:null}
      {tab==='Activity'?<Activity canViewAudit={hasPermission(permissions,'bids.audit.view')} currentUser={currentUser}/>:null}
    </div>
  </div>;
}

function Overview({bid,deadline}:{bid:DemoBid;deadline:{tone:string;label:string}}){return <><section className="workspace-kpis"><article><span>Completion</span><strong>{bid.progress}%</strong><progress value={bid.progress} max="100"/></article><article><span>Readiness score</span><strong>{bid.readiness}%</strong><small>{bid.readiness>=80?'Final checks':'Work remains'}</small></article><article><span>Qualification</span><strong>{bid.qualificationScore}/100</strong><small>{bid.qualificationScore>=70?'Pursue':'Management review'}</small></article><article><span>Bid spend</span><strong>{formatMoney(bid.spendMinor)}</strong><small>Budget UGX 16.5M</small></article></section><div className="workspace-grid"><section className="panel workspace-panel"><header><div><p className="panel-kicker">OPPORTUNITY SUMMARY</p><h2>Executive overview</h2></div><ClipboardCheck/></header><p>{bid.description}</p><dl className="detail-list"><div><dt>Procuring entity</dt><dd>{bid.organization}</dd></div><div><dt>Procurement method</dt><dd>{bid.procurementMethod}</dd></div><div><dt>Source</dt><dd>{bid.source}</dd></div><div><dt>Published</dt><dd>{bid.published||'Not recorded'}</dd></div><div><dt>Expected award</dt><dd>{bid.expectedAward||'Not recorded'}</dd></div><div><dt>Priority</dt><dd>{bid.priority}</dd></div></dl></section><section className="panel workspace-panel"><header><div><p className="panel-kicker">DEADLINE CONTROL</p><h2>Important dates</h2></div><CalendarClock/></header><div className={`deadline-callout deadline-${deadline.tone}`}><Clock3/><div><strong>{deadline.label}</strong><span>{new Date(bid.deadline).toLocaleString('en-UG',{dateStyle:'full',timeStyle:'short'})}</span></div></div><ul className="date-list"><li><span>Clarification deadline</span><strong>03 Sep · 17:00</strong></li><li><span>Internal review</span><strong>04 Sep · 10:00</strong></li><li><span>Submission approval</span><strong>04 Sep · 15:00</strong></li></ul></section><section className="panel workspace-panel"><header><div><p className="panel-kicker">EXCEPTIONS</p><h2>Outstanding requirements</h2></div><AlertTriangle/></header><ul className="exception-list"><li><span>Manufacturer authorisations</span><em>Due 04 Sep</em></li><li><span>Signed bid form</span><em>Not started</em></li><li><span>Director final approval</span><em>Pending</em></li></ul></section><section className="panel workspace-panel"><header><div><p className="panel-kicker">RECENT ACTIVITY</p><h2>Latest changes</h2></div><Clock3/></header><div className="mini-activity">{activities.slice(0,3).map((item)=><div key={item[0]}><i/><span><strong>{item[1]}</strong><small>{item[2]} · {item[0]}</small></span></div>)}</div></section></div></>}
function Qualification({bid,canApprove,working,action}:{bid:DemoBid;canApprove:boolean;working:boolean;action:(type:string,payload?:Record<string,unknown>)=>void}){const criteria=[['Strategic fit',15,90],['Relevant experience',15,85],['Technical capacity',15,80],['Financial capacity',12,76],['Eligibility',12,95],['Expected margin',10,72],['Deadline feasibility',8,70],['Competition',6,55],['Cash-flow exposure',7,68]];return <section className="panel workspace-panel full"><header><div><p className="panel-kicker">GO / NO-GO</p><h2>Qualification assessment</h2></div><span className="score-ring">{bid.qualificationScore}</span></header><div className="qualification-summary"><div><span>System recommendation</span><strong className={bid.qualificationScore>=70?'positive':'warning'}>{bid.qualificationScore>=70?'PURSUE':'REVIEW'}</strong><small>Weighted score supports management judgement; it does not make the decision.</small></div>{canApprove?<Button disabled={working||bid.stage!=='qualification'} title={bid.stage!=='qualification'?'Pursuit approval is only available during Qualification.':undefined} onClick={()=>action('approve_pursuit')}>Approve pursuit</Button>:<span className="locked-note"><ShieldCheck/> Director approval required</span>}</div><table className="criteria-table"><thead><tr><th>Criterion</th><th>Weight</th><th>Score</th><th>Weighted contribution</th></tr></thead><tbody>{criteria.map(([name,weight,score])=><tr key={name}><td>{name}</td><td>{weight}%</td><td><progress value={Number(score)} max="100"/> {score}</td><td>{Math.round(Number(weight)*Number(score)/100)}</td></tr>)}</tbody></table></section>}
function Requirements(){const complete=requirements.filter((item)=>item.status==='Verified').length;return <section className="panel workspace-panel full"><header><div><p className="panel-kicker">COMPLIANCE CONTROL</p><h2>Requirements checklist</h2></div><div className="completion-stat"><strong>{Math.round(complete/requirements.length*100)}%</strong><span>overall complete</span></div></header><div className="requirements-summary"><span><CheckCircle2/> {complete} verified</span><span><AlertTriangle/> {requirements.filter((item)=>item.mandatory&&item.status!=='Verified').length} mandatory outstanding</span><span><Clock3/> 1 due within 24 hours</span></div><table><thead><tr><th>Requirement</th><th>Category</th><th>Owner</th><th>Due</th><th>Mandatory</th><th>Status</th></tr></thead><tbody>{requirements.map((item)=><tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.category}</td><td>{item.owner}</td><td>{item.due}</td><td>{item.mandatory?'Yes':'No'}</td><td><span className="bid-status">{item.status}</span></td></tr>)}</tbody></table></section>}
function Pricing({canEdit}:{canEdit:boolean}){const direct=pricingLines.reduce((sum,line)=>sum+line.quantity*line.unitCost,0);const selling=pricingLines.reduce((sum,line)=>sum+line.quantity*line.selling,0);const tax=Math.round(selling*.18);return <><section className="workspace-kpis"><article><span>Direct cost</span><strong>{formatMoney(direct*100)}</strong></article><article><span>Markup value</span><strong>{formatMoney((selling-direct)*100)}</strong></article><article><span>VAT</span><strong>{formatMoney(tax*100)}</strong></article><article><span>Bid price</span><strong>{formatMoney((selling+tax)*100)}</strong></article></section><section className="panel workspace-panel full"><header><div><p className="panel-kicker">PRICING / BOQ</p><h2>Financial proposal v6</h2></div>{canEdit?<span className="access-chip">Editing permitted</span>:<span className="locked-note"><Eye/> View only</span>}</header><div className="table-scroll"><table><thead><tr><th>Description</th><th>Unit</th><th>Qty</th><th>Est. unit cost</th><th>Markup</th><th>Selling unit</th><th>Selling total</th></tr></thead><tbody>{pricingLines.map((line)=><tr key={line.description}><td>{line.description}</td><td>{line.unit}</td><td>{line.quantity}</td><td>{formatMoney(line.unitCost*100)}</td><td>{line.markup}%</td><td>{formatMoney(line.selling*100)}</td><td>{formatMoney(line.quantity*line.selling*100)}</td></tr>)}</tbody></table></div></section></>}
function Documents({canUpload}:{canUpload:boolean}){const docs=[['Tender document','v2','Verified','No expiry'],['Terms of reference','v1','Verified','No expiry'],['URA tax clearance','v3','Verified','18 Dec 2026'],['NSSF clearance','v2','Review required','30 Sep 2026'],['Financial proposal','v6','Draft','No expiry']];return <section className="panel workspace-panel full"><header><div><p className="panel-kicker">VERSIONED DOCUMENTS</p><h2>Bid document register</h2></div>{canUpload?<span className="access-chip"><FileText/> Upload permitted</span>:<span className="locked-note"><Eye/> View only</span>}</header><p className="section-note">Company compliance documents can be linked from the reusable library without replacing their source version.</p><table><thead><tr><th>Document</th><th>Version</th><th>Uploaded by</th><th>Verification</th><th>Expiry</th></tr></thead><tbody>{docs.map((doc)=><tr key={doc[0]}><td><FileText/> <strong>{doc[0]}</strong></td><td>{doc[1]}</td><td>Irene Adoch</td><td><span className="bid-status">{doc[2]}</span></td><td>{doc[3]}</td></tr>)}</tbody></table></section>}
function TeamTasks({canManage}:{canManage:boolean}){const tasks=[['Finalise manufacturer letters','Technical Lead','04 Sep','In Progress'],['Review financial proposal','Finance','04 Sep','Review'],['Sign bid form','Director','05 Sep','Not Started'],['Assemble portal package','Bid Lead','05 Sep','In Progress']];return <div className="workspace-grid"><section className="panel workspace-panel"><header><div><p className="panel-kicker">BID TEAM</p><h2>Responsibilities</h2></div>{canManage?<span className="access-chip">Manage team</span>:null}</header><ul className="team-list"><li><span>IA</span><div><strong>Irene Adoch</strong><small>Bid Lead · 4 tasks</small></div></li><li><span>PM</span><div><strong>Peter Mugisha</strong><small>Finance · 2 tasks</small></div></li><li><span>AN</span><div><strong>Amina Nsubuga</strong><small>Director · 1 approval</small></div></li></ul></section><section className="panel workspace-panel"><header><div><p className="panel-kicker">TASK CONTROL</p><h2>Open tasks</h2></div><BriefcaseBusiness/></header>{tasks.map((task)=><div className="task-row" key={task[0]}><span><strong>{task[0]}</strong><small>{task[1]} · Due {task[2]}</small></span><em>{task[3]}</em></div>)}</section></div>}
function Expenses({canCreate,canApprove}:{canCreate:boolean;canApprove:boolean}){const rows=[['BEX-2026-041','Tender document','Ministry cashier','UGX 250,000','Paid'],['BEX-2026-044','Site visit transport','Star Africa fleet','UGX 680,000','Approved'],['BEX-2026-047','Bid security fee','Demo Bank Uganda','UGX 2,150,000','Submitted'],['BEX-2026-052','Printing & binding','Kampala Print Demo','UGX 420,000','Draft']];return <section className="panel workspace-panel full"><header><div><p className="panel-kicker">BID PREPARATION COST</p><h2>Budget vs actual</h2></div><div className="access-tags">{canCreate?<span>Record permitted</span>:null}{canApprove?<span>Approve permitted</span>:null}</div></header><section className="expense-meter"><div><span>Approved budget</span><strong>UGX 16.5M</strong></div><div><span>Actual spend</span><strong>UGX 12.4M</strong></div><progress value="75" max="100"/><em>75% utilised</em></section><table><thead><tr><th>Expense</th><th>Category</th><th>Payee</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map((row)=><tr key={row[0]}>{row.map((cell,index)=><td key={cell}>{index===0?<strong>{cell}</strong>:index===4?<span className="bid-status">{cell}</span>:cell}</td>)}</tr>)}</tbody></table></section>}
function Security({canManage}:{canManage:boolean}){return <section className="panel workspace-panel full"><header><div><p className="panel-kicker">FINANCIAL EXPOSURE</p><h2>Bid security</h2></div>{canManage?<span className="access-chip">Manage security</span>:<span className="locked-note"><Eye/> View only</span>}</header><div className="security-card"><span><Landmark/></span><div><p>Bank guarantee</p><h3>UGX 30,400,000</h3><small>Demo Bank Uganda · BG-2026-00881</small></div><dl><div><dt>Issued</dt><dd>28 Aug 2026</dd></div><div><dt>Expires</dt><dd>04 Jan 2027</dd></div><div><dt>Fee</dt><dd>UGX 2.15M</dd></div><div><dt>Status</dt><dd><span className="bid-status">Active</span></dd></div></dl></div></section>}
function Approvals({canApprove,working,action}:{canApprove:boolean;working:boolean;action:(type:string)=>void}){const approvals=[['Pursuit approval','Amina Nsubuga','Approved','18 Aug · 14:20'],['Pricing review','Peter Mugisha','Approved','02 Sep · 09:42'],['Technical review','Technical Lead','Approved','01 Sep · 15:05'],['Final submission','Amina Nsubuga','Pending','—']];return <section className="panel workspace-panel full"><header><div><p className="panel-kicker">CONTROLLED DECISIONS</p><h2>Approval trail</h2></div>{canApprove?<Button disabled={working} onClick={()=>action('final_approval')}><Check/> Record final approval</Button>:<span className="locked-note"><ShieldCheck/> Approval permission required</span>}</header><div className="approval-flow">{approvals.map((approval,index)=><div key={approval[0]} className={approval[2]==='Approved'?'done':'pending'}><span>{approval[2]==='Approved'?<Check/>:index+1}</span><div><strong>{approval[0]}</strong><small>{approval[1]} · {approval[3]}</small></div><em>{approval[2]}</em></div>)}</div></section>}
function Clarifications(){return <div className="workspace-grid"><section className="panel workspace-panel"><header><div><p className="panel-kicker">CLARIFICATIONS</p><h2>Questions and responses</h2></div><MessageSquareText/></header><div className="clarification"><strong>CL-004 · Warranty response time</strong><span>Raised 26 Aug · Response received 29 Aug</span><p>The procuring entity confirmed a maximum onsite response time of 48 hours.</p><em>Closed</em></div><div className="clarification"><strong>CL-005 · Delivery phasing</strong><span>Raised 28 Aug · Awaiting response</span><p>Confirm whether delivery may be phased across regional hospitals.</p><em>Open</em></div></section><section className="panel workspace-panel"><header><div><p className="panel-kicker">ADDENDA</p><h2>Tender changes</h2></div><FileCheck2/></header><div className="addendum"><span>02</span><div><strong>Addendum 02</strong><small>31 Aug 2026</small><p>Delivery schedule updated. Technical requirements flagged for re-review.</p></div></div></section></div>}
function Submission({readiness,canSubmit,working,action}:{readiness:{ready:boolean;blockers:string[]};canSubmit:boolean;working:boolean;action:(type:string)=>void}){return <div className="workspace-grid submission-grid"><section className={`panel readiness-card ${readiness.ready?'ready':'blocked'}`}><span>{readiness.ready?<CheckCircle2/>:<AlertTriangle/>}</span><p>SUBMISSION READINESS</p><h2>{readiness.ready?'READY TO SUBMIT':'NOT READY'}</h2><small>{readiness.ready?'All controlled checks have passed.':`${readiness.blockers.length} blockers must be resolved.`}</small><Button disabled={!readiness.ready||!canSubmit||working} title={!canSubmit?'Your role cannot record final submission.':!readiness.ready?'Resolve every listed blocker before submission.':undefined} onClick={()=>action('submit')}>Record submission</Button></section><section className="panel workspace-panel"><header><div><p className="panel-kicker">EXACT BLOCKERS</p><h2>Readiness checklist</h2></div><ClipboardCheck/></header><ul className="blocker-list">{readiness.blockers.map((blocker)=><li key={blocker}><AlertTriangle/><span>{blocker}</span></li>)}<li className="passed"><Check/><span>Required final documents are present.</span></li><li className="passed"><Check/><span>Bid security is active beyond the validity threshold.</span></li></ul></section><section className="panel workspace-panel full"><header><div><p className="panel-kicker">SUBMISSION PACKAGE</p><h2>Final package manifest</h2></div><FileText/></header><div className="manifest-grid"><div><Check/> Technical proposal.pdf <span>Verified</span></div><div><Check/> Financial proposal.pdf <span>Approved</span></div><div><Check/> Bid security.pdf <span>Valid</span></div><div><AlertTriangle/> Signed bid form.pdf <span>Missing</span></div></div><p className="section-note">ZIP generation is not enabled in the demo provider. Individual versioned documents remain available from Documents.</p></section></div>}
function Result({bid,canAward,working,action}:{bid:DemoBid;canAward:boolean;working:boolean;action:(type:string,payload?:Record<string,unknown>)=>void}){const decided=['won','lost'].includes(bid.stage);return <section className="panel workspace-panel full"><header><div><p className="panel-kicker">RESULT / AWARD</p><h2>{decided?labelStage(bid.stage):'Awaiting procuring entity decision'}</h2></div>{canAward&&bid.stage==='awaiting_result'?<div className="result-actions"><Button disabled={working} onClick={()=>action('record_result',{result:'won'})}>Record win</Button><Button variant="outline" disabled={working} onClick={()=>action('record_result',{result:'lost'})}>Record loss</Button></div>:null}</header>{bid.stage==='won'?<div className="won-panel"><CheckCircle2/><div><strong>Ready for project handover</strong><p>Client, scope, contract value, bid team, BOQ and award documents are prepared for conversion.</p><Button disabled title="Projects integration point is prepared; deep project rebuilding is outside this phase.">Convert to project</Button></div></div>:bid.stage==='lost'?<div className="loss-panel"><ReceiptText/><div><strong>Loss analysis recorded</strong><p>Primary reason: competitor price advantage. Lesson: secure earlier manufacturer quotations for higher-volume discounts.</p></div></div>:<div className="waiting-result"><Clock3/><p>No result has been recorded. Decision follow-up is scheduled for {bid.expectedAward||'the expected award date'}.</p></div>}</section>}
function Activity({canViewAudit,currentUser}:{canViewAudit:boolean;currentUser:string}){return <section className="panel workspace-panel full"><header><div><p className="panel-kicker">ACTIVITY & AUDIT</p><h2>Immutable bid timeline</h2></div>{canViewAudit?<span className="access-chip"><ShieldCheck/> Audit access</span>:null}</header><div className="timeline">{activities.map((item,index)=><div key={item[0]}><span>{index+1}</span><div><strong>{item[1]}</strong><p>{item[3]}</p><small>{item[2]} · {item[0]}</small></div></div>)}<div><span>{activities.length+1}</span><div><strong>Workspace viewed</strong><p>Role-filtered opportunity workspace opened.</p><small>{currentUser} · Current session</small></div></div></div></section>}
