import Link from 'next/link';
import { AlertTriangle, ArrowUpRight, CircleDollarSign, FolderKanban, Landmark, ReceiptText } from 'lucide-react';
import { kpis, money, projects } from '@/lib/demo-data';

export function ExecutiveDashboard({firstName}:{firstName:string}){
  return <div className="page-content executive-dashboard">
    <section className="page-heading"><div><p className="eyebrow">EXECUTIVE COMMAND CENTRE</p><h1>Good morning, {firstName}</h1><p className="overview-title">Star Africa operations overview</p><p>Sensitive company-wide performance, cash and delivery signals for authorised leadership.</p></div><Link className="dashboard-link-button" href="/projects">Open project portfolio <ArrowUpRight/></Link></section>
    <section className="kpi-grid" aria-label="Executive financial indicators">{kpis.map((kpi,index)=><article className="kpi-card" key={kpi.label}><div className="kpi-top"><span>{kpi.label}</span><span className={`metric-icon metric-${index}`}>{index===0?<CircleDollarSign/>:index===1?<Landmark/>:index===2?<ReceiptText/>:<FolderKanban/>}</span></div><strong>{money(kpi.value)}</strong><p className={kpi.tone}>{kpi.delta}</p></article>)}</section>
    <section className="dashboard-grid"><article className="panel portfolio-summary"><header><div><p className="panel-kicker">DELIVERY PORTFOLIO</p><h2>Projects requiring leadership attention</h2></div><Link href="/projects">View all</Link></header><div className="table-scroll"><table className="attention-project-table"><thead><tr><th>Project</th><th>Progress</th><th>Health</th><th>Reason</th><th>Action</th></tr></thead><tbody>{projects.slice(0,4).map((project,index)=><tr key={project.name}><td><strong>{project.name}</strong><small>{project.code}</small></td><td><span className="dashboard-progress"><i style={{width:`${project.progress}%`}}/></span><small>{project.progress}% complete</small></td><td><span className={`health ${index===1?'health-at_risk':'health-on_track'}`}>{index===1?'At Risk':'On Track'}</span></td><td>{index===1?'Schedule pressure requires intervention':'Upcoming milestone review'}</td><td><Link href="/projects">Open</Link></td></tr>)}</tbody></table></div></article><article className="panel attention-card"><header><p className="panel-kicker">ATTENTION QUEUE</p><h2>Decisions and exceptions</h2></header><div className="attention-rows">{['Two project variations await approval','Receivables exceed 30-day target','One material delivery affects a milestone','Three bid approvals are due this week'].map((item,index)=><div key={item}><span className="attention-icon"><AlertTriangle/></span><span><strong>{item}</strong><small>{index<2?'Financial · Approval':'Operational · Review'}</small></span><ArrowUpRight/></div>)}</div></article></section>
  </div>;
}
