'use client';
import { useMemo,useState } from 'react';
import { Download,Plus,Search,SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { StatusBadge } from '@/components/brand-primitives';
import type { ModuleConfig } from '@/lib/modules';

export function GenericWorkspace({config,canCreate}:{config:ModuleConfig;canCreate:boolean}){
  const [query,setQuery]=useState('');const [activeTab,setActiveTab]=useState(config.tabs[0]);
  const rows=useMemo(()=>config.rows.filter((row)=>!query||row.some((cell)=>cell.toLowerCase().includes(query.toLowerCase()))),[query,config.rows]);
  const exportCsv=()=>{const csv=[config.columns,...rows].map((row)=>row.map((v)=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`${config.slug}.csv`;a.click();URL.revokeObjectURL(url)};
  return <div className="page-content module-content"><section className="module-heading"><div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p>{config.description}</p></div><div className="heading-actions"><Button variant="outline" onClick={exportCsv}><Download/>Export</Button>{canCreate?<Button><Plus/>{config.primaryAction}</Button>:null}</div></section>{config.workflow?<section className="workflow-strip">{config.workflow.map((step,index)=><div key={step}><span>{String(index+1).padStart(2,'0')}</span><strong>{step}</strong></div>)}</section>:null}<section className="module-stats">{config.stats.map((stat)=><article key={stat.label}><span>{stat.label}</span><strong>{stat.value}</strong><small>{stat.note}</small></article>)}</section><section className="panel records-panel"><div className="module-tabs">{config.tabs.map((tab)=><button className={tab===activeTab?'active':''} onClick={()=>setActiveTab(tab)} key={tab}>{tab}</button>)}</div><div className="records-toolbar"><div><h2>{activeTab}</h2><span>{rows.length} permitted records</span></div><div><label><Search/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search records"/></label><button className="toolbar-button"><SlidersHorizontal/>Filters</button></div></div><div className="table-scroll"><table className="records-table"><thead><tr>{config.columns.map((column)=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row)=><tr key={row.join('-')}>{row.map((value,index)=><td key={`${index}-${value}`}>{index===0?<strong>{value}</strong>:index===row.length-1?<StatusBadge>{value}</StatusBadge>:value}</td>)}</tr>)}</tbody></table></div></section></div>;
}
