import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const id = (name = 'id') => text(name).primaryKey();
const timestamps = { createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull() };
const moneyColumns = { currency: text('currency', { length: 3 }).notNull().default('UGX'), amountMinor: text('amount_minor').notNull().default('0') };

export const companies = sqliteTable('companies', {
  id: id(), name: text('name').notNull(), countryCode: text('country_code').notNull().default('UG'), baseCurrency: text('base_currency').notNull().default('UGX'), timezone: text('timezone').notNull().default('Africa/Kampala'), ...timestamps,
});
export const users = sqliteTable('users', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), externalIdentityId: text('external_identity_id').notNull(), email: text('email').notNull(), displayName: text('display_name').notNull(), department: text('department'), status: text('status').notNull().default('active'), ...timestamps,
}, (t) => [uniqueIndex('uq_users_company_external').on(t.companyId, t.externalIdentityId), index('idx_users_company_email').on(t.companyId, t.email)]);
export const roles = sqliteTable('roles', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), description: text('description'), readOnly: integer('read_only', { mode: 'boolean' }).notNull().default(false), ...timestamps,
}, (t) => [uniqueIndex('uq_roles_company_name').on(t.companyId, t.name)]);
export const permissions = sqliteTable('permissions', { id: id(), code: text('code').notNull().unique(), description: text('description').notNull() });
export const userRoles = sqliteTable('user_roles', { userId: text('user_id').notNull().references(() => users.id), roleId: text('role_id').notNull().references(() => roles.id), assignedAt: integer('assigned_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [uniqueIndex('uq_user_roles').on(t.userId, t.roleId)]);
export const rolePermissions = sqliteTable('role_permissions', { roleId: text('role_id').notNull().references(() => roles.id), permissionId: text('permission_id').notNull().references(() => permissions.id) }, (t) => [uniqueIndex('uq_role_permissions').on(t.roleId, t.permissionId)]);

export const customers = sqliteTable('customers', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), tin: text('tin'), email: text('email'), phone: text('phone'), address: text('address'), status: text('status').notNull().default('active'), ...timestamps,
}, (t) => [uniqueIndex('uq_customers_company_code').on(t.companyId, t.code), index('idx_customers_company_name').on(t.companyId, t.name)]);
export const suppliers = sqliteTable('suppliers', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), tin: text('tin'), vatRegistered: integer('vat_registered', { mode: 'boolean' }).notNull().default(false), creditTermsDays: integer('credit_terms_days').notNull().default(0), email: text('email'), phone: text('phone'), status: text('status').notNull().default('active'), ...timestamps,
}, (t) => [uniqueIndex('uq_suppliers_company_code').on(t.companyId, t.code), index('idx_suppliers_company_name').on(t.companyId, t.name)]);

export const bids = sqliteTable('bids', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), title: text('title').notNull(), organization: text('organization').notNull(), category: text('category'), source: text('source'), sourceUrl: text('source_url'), publishedAt: integer('published_at', { mode: 'timestamp_ms' }), closesAt: integer('closes_at', { mode: 'timestamp_ms' }).notNull(), currency: text('currency').notNull().default('UGX'), estimatedValueMinor: text('estimated_value_minor'), status: text('status').notNull().default('new'), assignedTo: text('assigned_to').references(() => users.id), ...timestamps,
}, (t) => [uniqueIndex('uq_bids_company_reference').on(t.companyId, t.reference), index('idx_bids_status_closes').on(t.companyId, t.status, t.closesAt)]);
export const bidRequirements = sqliteTable('bid_requirements', {
  id: id(), bidId: text('bid_id').notNull().references(() => bids.id), requirement: text('requirement').notNull(), required: integer('required', { mode: 'boolean' }).notNull().default(true), uploaded: integer('uploaded', { mode: 'boolean' }).notNull().default(false), verified: integer('verified', { mode: 'boolean' }).notNull().default(false), expiresAt: integer('expires_at', { mode: 'timestamp_ms' }), notes: text('notes'), ...timestamps,
}, (t) => [index('idx_bid_requirements_bid').on(t.bidId)]);
export const bidExpenses = sqliteTable('bid_expenses', {
  id: id(), bidId: text('bid_id').notNull().references(() => bids.id), category: text('category').notNull(), description: text('description').notNull(), ...moneyColumns, journalEntryId: text('journal_entry_id'), incurredAt: integer('incurred_at', { mode: 'timestamp_ms' }).notNull(), createdBy: text('created_by').notNull().references(() => users.id), ...timestamps,
}, (t) => [index('idx_bid_expenses_bid').on(t.bidId)]);

export const projectStages = sqliteTable('project_stages', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), sequence: integer('sequence').notNull(), enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true), ...timestamps,
}, (t) => [uniqueIndex('uq_project_stages_company_sequence').on(t.companyId, t.sequence)]);
export const projects = sqliteTable('projects', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), customerId: text('customer_id').notNull().references(() => customers.id), bidId: text('bid_id').references(() => bids.id), category: text('category'), location: text('location'), contractCurrency: text('contract_currency').notNull().default('UGX'), contractValueMinor: text('contract_value_minor').notNull(), budgetMinor: text('budget_minor').notNull().default('0'), retentionBasisPoints: integer('retention_basis_points').notNull().default(500), startsAt: integer('starts_at', { mode: 'timestamp_ms' }), plannedCompletionAt: integer('planned_completion_at', { mode: 'timestamp_ms' }), stageId: text('stage_id').references(() => projectStages.id), status: text('status').notNull().default('active'), completionBasisPoints: integer('completion_basis_points').notNull().default(0), projectManagerId: text('project_manager_id').references(() => users.id), ...timestamps,
}, (t) => [uniqueIndex('uq_projects_company_code').on(t.companyId, t.code), index('idx_projects_customer').on(t.customerId), index('idx_projects_bid').on(t.bidId)]);
export const projectTasks = sqliteTable('project_tasks', {
  id: id(), projectId: text('project_id').notNull().references(() => projects.id), title: text('title').notNull(), assigneeId: text('assignee_id').references(() => users.id), dueAt: integer('due_at', { mode: 'timestamp_ms' }), status: text('status').notNull().default('open'), priority: text('priority').notNull().default('normal'), ...timestamps,
}, (t) => [index('idx_project_tasks_project_status').on(t.projectId, t.status)]);

export const procurementRequests = sqliteTable('procurement_requests', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), projectId: text('project_id').references(() => projects.id), bidId: text('bid_id').references(() => bids.id), department: text('department'), purpose: text('purpose').notNull(), currency: text('currency').notNull().default('UGX'), totalMinor: text('total_minor').notNull(), status: text('status').notNull().default('draft'), requestedBy: text('requested_by').notNull().references(() => users.id), ...timestamps,
}, (t) => [uniqueIndex('uq_procurement_requests_reference').on(t.companyId, t.reference), index('idx_procurement_project_status').on(t.projectId, t.status)]);
export const purchaseOrders = sqliteTable('purchase_orders', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), requestId: text('request_id').references(() => procurementRequests.id), supplierId: text('supplier_id').notNull().references(() => suppliers.id), projectId: text('project_id').references(() => projects.id), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull(), taxMinor: text('tax_minor').notNull().default('0'), totalMinor: text('total_minor').notNull(), status: text('status').notNull().default('draft'), ...timestamps,
}, (t) => [uniqueIndex('uq_purchase_orders_reference').on(t.companyId, t.reference), index('idx_purchase_orders_supplier').on(t.supplierId)]);
export const goodsReceipts = sqliteTable('goods_receipts', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), purchaseOrderId: text('purchase_order_id').notNull().references(() => purchaseOrders.id), receivedAt: integer('received_at', { mode: 'timestamp_ms' }).notNull(), receivedBy: text('received_by').notNull().references(() => users.id), status: text('status').notNull().default('received'), notes: text('notes'), ...timestamps,
}, (t) => [uniqueIndex('uq_goods_receipts_reference').on(t.companyId, t.reference)]);

export const warehouses = sqliteTable('warehouses', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), location: text('location'), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_warehouses_company_code').on(t.companyId, t.code)]);
export const inventoryItems = sqliteTable('inventory_items', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), sku: text('sku').notNull(), name: text('name').notNull(), category: text('category').notNull(), unit: text('unit').notNull(), quantityMinor: text('quantity_minor').notNull().default('0'), reservedMinor: text('reserved_minor').notNull().default('0'), reorderLevelMinor: text('reorder_level_minor').notNull().default('0'), averageCostMinor: text('average_cost_minor').notNull().default('0'), currency: text('currency').notNull().default('UGX'), tracksBatch: integer('tracks_batch', { mode: 'boolean' }).notNull().default(false), ...timestamps,
}, (t) => [uniqueIndex('uq_inventory_company_sku').on(t.companyId, t.sku), index('idx_inventory_company_category').on(t.companyId, t.category)]);
export const stockMovements = sqliteTable('stock_movements', {
  id: id(), itemId: text('item_id').notNull().references(() => inventoryItems.id), warehouseId: text('warehouse_id').notNull().references(() => warehouses.id), projectId: text('project_id').references(() => projects.id), goodsReceiptId: text('goods_receipt_id').references(() => goodsReceipts.id), movementType: text('movement_type').notNull(), quantityMinor: text('quantity_minor').notNull(), unitCostMinor: text('unit_cost_minor'), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(), createdBy: text('created_by').notNull().references(() => users.id), ...timestamps,
}, (t) => [index('idx_stock_movements_item_date').on(t.itemId, t.occurredAt), index('idx_stock_movements_project').on(t.projectId)]);

export const invoices = sqliteTable('invoices', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), number: text('number').notNull(), customerId: text('customer_id').notNull().references(() => customers.id), projectId: text('project_id').references(() => projects.id), issueDate: integer('issue_date', { mode: 'timestamp_ms' }).notNull(), dueDate: integer('due_date', { mode: 'timestamp_ms' }).notNull(), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull(), discountMinor: text('discount_minor').notNull().default('0'), taxMinor: text('tax_minor').notNull().default('0'), retentionMinor: text('retention_minor').notNull().default('0'), totalMinor: text('total_minor').notNull(), paidMinor: text('paid_minor').notNull().default('0'), status: text('status').notNull().default('draft'), journalEntryId: text('journal_entry_id'), ...timestamps,
}, (t) => [uniqueIndex('uq_invoices_company_number').on(t.companyId, t.number), index('idx_invoices_customer_due').on(t.customerId, t.dueDate), index('idx_invoices_project').on(t.projectId)]);
export const invoiceLines = sqliteTable('invoice_lines', { id: id(), invoiceId: text('invoice_id').notNull().references(() => invoices.id), description: text('description').notNull(), quantityMinor: text('quantity_minor').notNull(), unitPriceMinor: text('unit_price_minor').notNull(), taxBasisPoints: integer('tax_basis_points').notNull().default(0), lineTotalMinor: text('line_total_minor').notNull(), sequence: integer('sequence').notNull() }, (t) => [index('idx_invoice_lines_invoice').on(t.invoiceId)]);
export const payments = sqliteTable('payments', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), customerId: text('customer_id').references(() => customers.id), supplierId: text('supplier_id').references(() => suppliers.id), projectId: text('project_id').references(() => projects.id), ...moneyColumns, receivedOrPaidAt: integer('received_or_paid_at', { mode: 'timestamp_ms' }).notNull(), method: text('method').notNull(), bankReference: text('bank_reference'), status: text('status').notNull().default('expected'), journalEntryId: text('journal_entry_id'), ...timestamps,
}, (t) => [uniqueIndex('uq_payments_company_reference').on(t.companyId, t.reference), index('idx_payments_customer').on(t.customerId)]);
export const paymentAllocations = sqliteTable('payment_allocations', { id: id(), paymentId: text('payment_id').notNull().references(() => payments.id), invoiceId: text('invoice_id').notNull().references(() => invoices.id), amountMinor: text('amount_minor').notNull(), createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [uniqueIndex('uq_payment_invoice_allocation').on(t.paymentId, t.invoiceId), index('idx_allocations_invoice').on(t.invoiceId)]);
export const supplierBills = sqliteTable('supplier_bills', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), supplierId: text('supplier_id').notNull().references(() => suppliers.id), purchaseOrderId: text('purchase_order_id').references(() => purchaseOrders.id), invoiceNumber: text('invoice_number').notNull(), issueDate: integer('issue_date', { mode: 'timestamp_ms' }).notNull(), dueDate: integer('due_date', { mode: 'timestamp_ms' }).notNull(), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull(), taxMinor: text('tax_minor').notNull().default('0'), totalMinor: text('total_minor').notNull(), paidMinor: text('paid_minor').notNull().default('0'), status: text('status').notNull().default('open'), journalEntryId: text('journal_entry_id'), ...timestamps,
}, (t) => [uniqueIndex('uq_supplier_bills_supplier_number').on(t.supplierId, t.invoiceNumber), index('idx_supplier_bills_due_status').on(t.dueDate, t.status)]);

export const fiscalYears = sqliteTable('fiscal_years', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), startsAt: integer('starts_at', { mode: 'timestamp_ms' }).notNull(), endsAt: integer('ends_at', { mode: 'timestamp_ms' }).notNull(), status: text('status').notNull().default('open'), ...timestamps }, (t) => [uniqueIndex('uq_fiscal_year_company_name').on(t.companyId, t.name)]);
export const accountingPeriods = sqliteTable('accounting_periods', { id: id(), fiscalYearId: text('fiscal_year_id').notNull().references(() => fiscalYears.id), name: text('name').notNull(), startsAt: integer('starts_at', { mode: 'timestamp_ms' }).notNull(), endsAt: integer('ends_at', { mode: 'timestamp_ms' }).notNull(), status: text('status').notNull().default('open'), lockedBy: text('locked_by').references(() => users.id), lockedAt: integer('locked_at', { mode: 'timestamp_ms' }) }, (t) => [uniqueIndex('uq_accounting_period_year_name').on(t.fiscalYearId, t.name)]);
export const accounts = sqliteTable('accounts', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), type: text('type').notNull(), normalBalance: text('normal_balance').notNull(), parentId: text('parent_id'), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_accounts_company_code').on(t.companyId, t.code)]);
export const journalEntries = sqliteTable('journal_entries', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), number: text('number').notNull(), periodId: text('period_id').notNull().references(() => accountingPeriods.id), entryDate: integer('entry_date', { mode: 'timestamp_ms' }).notNull(), sourceType: text('source_type').notNull(), sourceId: text('source_id'), memo: text('memo').notNull(), currency: text('currency').notNull().default('UGX'), status: text('status').notNull().default('draft'), reversalOfId: text('reversal_of_id'), createdBy: text('created_by').notNull().references(() => users.id), postedBy: text('posted_by').references(() => users.id), postedAt: integer('posted_at', { mode: 'timestamp_ms' }), ...timestamps,
}, (t) => [uniqueIndex('uq_journal_entries_company_number').on(t.companyId, t.number), uniqueIndex('uq_journal_source_idempotency').on(t.companyId, t.sourceType, t.sourceId), index('idx_journal_entries_period_status').on(t.periodId, t.status)]);
export const journalLines = sqliteTable('journal_lines', { id: id(), journalEntryId: text('journal_entry_id').notNull().references(() => journalEntries.id), accountId: text('account_id').notNull().references(() => accounts.id), description: text('description'), debitMinor: text('debit_minor').notNull().default('0'), creditMinor: text('credit_minor').notNull().default('0'), customerId: text('customer_id').references(() => customers.id), supplierId: text('supplier_id').references(() => suppliers.id), projectId: text('project_id').references(() => projects.id), sequence: integer('sequence').notNull() }, (t) => [index('idx_journal_lines_entry').on(t.journalEntryId), index('idx_journal_lines_account').on(t.accountId)]);

export const bankAccounts = sqliteTable('bank_accounts', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), bankName: text('bank_name').notNull(), accountName: text('account_name').notNull(), maskedNumber: text('masked_number').notNull(), currency: text('currency').notNull().default('UGX'), ledgerAccountId: text('ledger_account_id').notNull().references(() => accounts.id), openingBalanceMinor: text('opening_balance_minor').notNull().default('0'), lastReconciledAt: integer('last_reconciled_at', { mode: 'timestamp_ms' }), ...timestamps });
export const bankTransactions = sqliteTable('bank_transactions', { id: id(), bankAccountId: text('bank_account_id').notNull().references(() => bankAccounts.id), externalId: text('external_id'), transactionDate: integer('transaction_date', { mode: 'timestamp_ms' }).notNull(), description: text('description').notNull(), reference: text('reference'), amountMinor: text('amount_minor').notNull(), status: text('status').notNull().default('unmatched'), journalEntryId: text('journal_entry_id').references(() => journalEntries.id), ...timestamps }, (t) => [uniqueIndex('uq_bank_transaction_external').on(t.bankAccountId, t.externalId), index('idx_bank_transactions_account_date').on(t.bankAccountId, t.transactionDate)]);
export const bankReconciliations = sqliteTable('bank_reconciliations', { id: id(), bankAccountId: text('bank_account_id').notNull().references(() => bankAccounts.id), periodEnd: integer('period_end', { mode: 'timestamp_ms' }).notNull(), statementBalanceMinor: text('statement_balance_minor').notNull(), ledgerBalanceMinor: text('ledger_balance_minor').notNull(), differenceMinor: text('difference_minor').notNull(), status: text('status').notNull().default('draft'), finalizedBy: text('finalized_by').references(() => users.id), finalizedAt: integer('finalized_at', { mode: 'timestamp_ms' }), ...timestamps }, (t) => [uniqueIndex('uq_bank_reconciliation_period').on(t.bankAccountId, t.periodEnd)]);
export const retentions = sqliteTable('retentions', { id: id(), projectId: text('project_id').notNull().references(() => projects.id), invoiceId: text('invoice_id').references(() => invoices.id), basisPoints: integer('basis_points').notNull(), baseMinor: text('base_minor').notNull(), amountMinor: text('amount_minor').notNull(), withheldAt: integer('withheld_at', { mode: 'timestamp_ms' }), expectedReleaseAt: integer('expected_release_at', { mode: 'timestamp_ms' }), actualReleaseAt: integer('actual_release_at', { mode: 'timestamp_ms' }), receivedMinor: text('received_minor').notNull().default('0'), status: text('status').notNull().default('withheld'), ...timestamps }, (t) => [index('idx_retentions_project_status').on(t.projectId, t.status), index('idx_retentions_release').on(t.expectedReleaseAt)]);

export const employees = sqliteTable('employees', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), employeeNumber: text('employee_number').notNull(), name: text('name').notNull(), department: text('department'), jobTitle: text('job_title'), email: text('email'), phone: text('phone'), hiredAt: integer('hired_at', { mode: 'timestamp_ms' }), currency: text('currency').notNull().default('UGX'), salaryMinor: text('salary_minor').notNull(), paymentMethod: text('payment_method'), status: text('status').notNull().default('active'), ...timestamps }, (t) => [uniqueIndex('uq_employees_company_number').on(t.companyId, t.employeeNumber)]);
export const payrollRuns = sqliteTable('payroll_runs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), periodId: text('period_id').notNull().references(() => accountingPeriods.id), currency: text('currency').notNull().default('UGX'), grossMinor: text('gross_minor').notNull().default('0'), deductionsMinor: text('deductions_minor').notNull().default('0'), netMinor: text('net_minor').notNull().default('0'), status: text('status').notNull().default('draft'), journalEntryId: text('journal_entry_id').references(() => journalEntries.id), ...timestamps }, (t) => [uniqueIndex('uq_payroll_run_period').on(t.companyId, t.periodId)]);

export const documents = sqliteTable('documents', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), storageKey: text('storage_key').notNull(), filename: text('filename').notNull(), mimeType: text('mime_type').notNull(), sizeBytes: integer('size_bytes').notNull(), sha256: text('sha256').notNull(), uploadedBy: text('uploaded_by').notNull().references(() => users.id), ocrStatus: text('ocr_status').notNull().default('uploaded'), verificationStatus: text('verification_status').notNull().default('pending'), ...timestamps }, (t) => [uniqueIndex('uq_documents_storage_key').on(t.storageKey), index('idx_documents_company_ocr').on(t.companyId, t.ocrStatus)]);
export const documentLinks = sqliteTable('document_links', { id: id(), documentId: text('document_id').notNull().references(() => documents.id), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), relationship: text('relationship').notNull(), createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [uniqueIndex('uq_document_links').on(t.documentId, t.entityType, t.entityId, t.relationship), index('idx_document_links_entity').on(t.entityType, t.entityId)]);
export const ocrJobs = sqliteTable('ocr_jobs', { id: id(), documentId: text('document_id').notNull().references(() => documents.id), provider: text('provider').notNull(), status: text('status').notNull().default('queued'), extractedJson: text('extracted_json'), confidenceBasisPoints: integer('confidence_basis_points'), errorCode: text('error_code'), attempts: integer('attempts').notNull().default(0), ...timestamps }, (t) => [index('idx_ocr_jobs_document').on(t.documentId)]);

export const approvalRequests = sqliteTable('approval_requests', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), amountMinor: text('amount_minor'), currency: text('currency'), status: text('status').notNull().default('pending'), currentStep: integer('current_step').notNull().default(1), requestedBy: text('requested_by').notNull().references(() => users.id), ...timestamps }, (t) => [index('idx_approvals_entity').on(t.entityType, t.entityId), index('idx_approvals_company_status').on(t.companyId, t.status)]);
export const approvalSteps = sqliteTable('approval_steps', { id: id(), requestId: text('request_id').notNull().references(() => approvalRequests.id), sequence: integer('sequence').notNull(), roleId: text('role_id').references(() => roles.id), approverId: text('approver_id').references(() => users.id), status: text('status').notNull().default('pending'), decisionNote: text('decision_note'), decidedAt: integer('decided_at', { mode: 'timestamp_ms' }) }, (t) => [uniqueIndex('uq_approval_step_sequence').on(t.requestId, t.sequence)]);
export const notifications = sqliteTable('notifications', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), userId: text('user_id').references(() => users.id), type: text('type').notNull(), title: text('title').notNull(), message: text('message').notNull(), entityType: text('entity_type'), entityId: text('entity_id'), priority: text('priority').notNull().default('normal'), readAt: integer('read_at', { mode: 'timestamp_ms' }), createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [index('idx_notifications_user_read').on(t.userId, t.readAt)]);
export const auditLogs = sqliteTable('audit_logs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), userId: text('user_id').references(() => users.id), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), oldValueJson: text('old_value_json'), newValueJson: text('new_value_json'), requestId: text('request_id'), ipHash: text('ip_hash'), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [index('idx_audit_entity_date').on(t.entityType, t.entityId, t.occurredAt), index('idx_audit_company_date').on(t.companyId, t.occurredAt)]);
export const emailLogs = sqliteTable('email_logs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), provider: text('provider').notNull(), mode: text('mode').notNull(), recipient: text('recipient').notNull(), subject: text('subject').notNull(), entityType: text('entity_type'), entityId: text('entity_id'), status: text('status').notNull(), providerMessageId: text('provider_message_id'), errorCode: text('error_code'), sentBy: text('sent_by').references(() => users.id), ...timestamps }, (t) => [index('idx_email_logs_entity').on(t.entityType, t.entityId)]);
export const backupJobs = sqliteTable('backup_jobs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), type: text('type').notNull(), provider: text('provider').notNull(), status: text('status').notNull(), sizeBytes: integer('size_bytes'), storageDestination: text('storage_destination'), restorePoint: text('restore_point'), verificationStatus: text('verification_status').notNull().default('pending'), requestedBy: text('requested_by').references(() => users.id), ...timestamps });
export const migrationJobs = sqliteTable('migration_jobs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), sourceType: text('source_type').notNull(), status: text('status').notNull().default('uploaded'), sourceDocumentId: text('source_document_id').references(() => documents.id), importedCount: integer('imported_count').notNull().default(0), errorCount: integer('error_count').notNull().default(0), reconciliationJson: text('reconciliation_json'), createdBy: text('created_by').notNull().references(() => users.id), ...timestamps });

// Supporting topology: these tables keep the less frequent workflows relational
// without coupling their rules to UI components or external providers.
export const companySettings = sqliteTable('company_settings', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), key: text('key').notNull(), valueJson: text('value_json').notNull(), updatedBy: text('updated_by').references(() => users.id), ...timestamps }, (t) => [uniqueIndex('uq_company_settings_key').on(t.companyId, t.key)]);
export const departments = sqliteTable('departments', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_departments_company_code').on(t.companyId, t.code)]);
export const businessCategories = sqliteTable('business_categories', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_business_categories_code').on(t.companyId, t.code)]);
export const customerContacts = sqliteTable('customer_contacts', { id: id(), customerId: text('customer_id').notNull().references(() => customers.id), name: text('name').notNull(), email: text('email'), phone: text('phone'), jobTitle: text('job_title'), primary: integer('primary_contact', { mode: 'boolean' }).notNull().default(false), ...timestamps }, (t) => [index('idx_customer_contacts_customer').on(t.customerId)]);
export const supplierContacts = sqliteTable('supplier_contacts', { id: id(), supplierId: text('supplier_id').notNull().references(() => suppliers.id), name: text('name').notNull(), email: text('email'), phone: text('phone'), jobTitle: text('job_title'), primary: integer('primary_contact', { mode: 'boolean' }).notNull().default(false), ...timestamps }, (t) => [index('idx_supplier_contacts_supplier').on(t.supplierId)]);
export const bidSources = sqliteTable('bid_sources', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), providerType: text('provider_type').notNull(), configurationJson: text('configuration_json'), enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true), lastRunAt: integer('last_run_at', { mode: 'timestamp_ms' }), ...timestamps }, (t) => [uniqueIndex('uq_bid_sources_company_name').on(t.companyId, t.name)]);
export const projectMilestones = sqliteTable('project_milestones', { id: id(), projectId: text('project_id').notNull().references(() => projects.id), name: text('name').notNull(), dueAt: integer('due_at', { mode: 'timestamp_ms' }), completedAt: integer('completed_at', { mode: 'timestamp_ms' }), status: text('status').notNull().default('planned'), certificateDocumentId: text('certificate_document_id').references(() => documents.id), ...timestamps }, (t) => [index('idx_project_milestones_due').on(t.projectId, t.dueAt)]);
export const projectExpenses = sqliteTable('project_expenses', { id: id(), projectId: text('project_id').notNull().references(() => projects.id), supplierId: text('supplier_id').references(() => suppliers.id), category: text('category').notNull(), description: text('description').notNull(), currency: text('currency').notNull().default('UGX'), amountMinor: text('amount_minor').notNull(), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(), journalEntryId: text('journal_entry_id').references(() => journalEntries.id), ...timestamps }, (t) => [index('idx_project_expenses_project_date').on(t.projectId, t.occurredAt)]);
export const procurementRequestItems = sqliteTable('procurement_request_items', { id: id(), requestId: text('request_id').notNull().references(() => procurementRequests.id), description: text('description').notNull(), quantityMinor: text('quantity_minor').notNull(), unit: text('unit').notNull(), estimatedUnitCostMinor: text('estimated_unit_cost_minor'), sequence: integer('sequence').notNull() }, (t) => [index('idx_procurement_request_items_request').on(t.requestId)]);
export const rfqs = sqliteTable('rfqs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), requestId: text('request_id').notNull().references(() => procurementRequests.id), issuedAt: integer('issued_at', { mode: 'timestamp_ms' }), closesAt: integer('closes_at', { mode: 'timestamp_ms' }).notNull(), status: text('status').notNull().default('draft'), ...timestamps }, (t) => [uniqueIndex('uq_rfqs_company_reference').on(t.companyId, t.reference)]);
export const supplierQuotations = sqliteTable('supplier_quotations', { id: id(), rfqId: text('rfq_id').notNull().references(() => rfqs.id), supplierId: text('supplier_id').notNull().references(() => suppliers.id), reference: text('reference'), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull(), taxMinor: text('tax_minor').notNull().default('0'), totalMinor: text('total_minor').notNull(), leadTimeDays: integer('lead_time_days'), selected: integer('selected', { mode: 'boolean' }).notNull().default(false), ...timestamps }, (t) => [uniqueIndex('uq_supplier_quotation').on(t.rfqId, t.supplierId)]);
export const purchaseOrderItems = sqliteTable('purchase_order_items', { id: id(), purchaseOrderId: text('purchase_order_id').notNull().references(() => purchaseOrders.id), inventoryItemId: text('inventory_item_id').references(() => inventoryItems.id), description: text('description').notNull(), quantityMinor: text('quantity_minor').notNull(), unit: text('unit').notNull(), unitCostMinor: text('unit_cost_minor').notNull(), lineTotalMinor: text('line_total_minor').notNull(), sequence: integer('sequence').notNull() }, (t) => [index('idx_purchase_order_items_order').on(t.purchaseOrderId)]);
export const goodsReceiptItems = sqliteTable('goods_receipt_items', { id: id(), goodsReceiptId: text('goods_receipt_id').notNull().references(() => goodsReceipts.id), purchaseOrderItemId: text('purchase_order_item_id').notNull().references(() => purchaseOrderItems.id), receivedQuantityMinor: text('received_quantity_minor').notNull(), acceptedQuantityMinor: text('accepted_quantity_minor').notNull(), rejectedQuantityMinor: text('rejected_quantity_minor').notNull().default('0'), notes: text('notes') }, (t) => [index('idx_goods_receipt_items_receipt').on(t.goodsReceiptId)]);
export const inventoryBatches = sqliteTable('inventory_batches', { id: id(), itemId: text('item_id').notNull().references(() => inventoryItems.id), warehouseId: text('warehouse_id').notNull().references(() => warehouses.id), batchNumber: text('batch_number').notNull(), serialNumber: text('serial_number'), manufacturer: text('manufacturer'), expiresAt: integer('expires_at', { mode: 'timestamp_ms' }), quantityMinor: text('quantity_minor').notNull(), ...timestamps }, (t) => [uniqueIndex('uq_inventory_batch').on(t.itemId, t.warehouseId, t.batchNumber), index('idx_inventory_batches_expiry').on(t.expiresAt)]);
export const creditNotes = sqliteTable('credit_notes', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), number: text('number').notNull(), invoiceId: text('invoice_id').notNull().references(() => invoices.id), currency: text('currency').notNull().default('UGX'), amountMinor: text('amount_minor').notNull(), reason: text('reason').notNull(), status: text('status').notNull().default('draft'), journalEntryId: text('journal_entry_id').references(() => journalEntries.id), ...timestamps }, (t) => [uniqueIndex('uq_credit_notes_company_number').on(t.companyId, t.number)]);
export const cheques = sqliteTable('cheques', { id: id(), bankAccountId: text('bank_account_id').notNull().references(() => bankAccounts.id), chequeNumber: text('cheque_number').notNull(), payee: text('payee').notNull(), currency: text('currency').notNull().default('UGX'), amountMinor: text('amount_minor').notNull(), chequeDate: integer('cheque_date', { mode: 'timestamp_ms' }).notNull(), purpose: text('purpose').notNull(), supplierId: text('supplier_id').references(() => suppliers.id), projectId: text('project_id').references(() => projects.id), approvalRequestId: text('approval_request_id').references(() => approvalRequests.id), status: text('status').notNull().default('prepared'), ...timestamps }, (t) => [uniqueIndex('uq_cheque_number_account').on(t.bankAccountId, t.chequeNumber)]);
export const payrollEntries = sqliteTable('payroll_entries', { id: id(), payrollRunId: text('payroll_run_id').notNull().references(() => payrollRuns.id), employeeId: text('employee_id').notNull().references(() => employees.id), grossMinor: text('gross_minor').notNull(), deductionsMinor: text('deductions_minor').notNull(), netMinor: text('net_minor').notNull(), status: text('status').notNull().default('calculated') }, (t) => [uniqueIndex('uq_payroll_entry_employee').on(t.payrollRunId, t.employeeId)]);
export const payrollComponents = sqliteTable('payroll_components', { id: id(), payrollEntryId: text('payroll_entry_id').notNull().references(() => payrollEntries.id), code: text('code').notNull(), name: text('name').notNull(), type: text('type').notNull(), amountMinor: text('amount_minor').notNull(), ruleVersion: text('rule_version') }, (t) => [index('idx_payroll_components_entry').on(t.payrollEntryId)]);
export const taxRules = sqliteTable('tax_rules', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), code: text('code').notNull(), basisPoints: integer('basis_points').notNull(), effectiveAt: integer('effective_at', { mode: 'timestamp_ms' }).notNull(), applicability: text('applicability').notNull(), inclusive: integer('inclusive', { mode: 'boolean' }).notNull().default(false), active: integer('active', { mode: 'boolean' }).notNull().default(true), configurationJson: text('configuration_json'), ...timestamps }, (t) => [uniqueIndex('uq_tax_rules_version').on(t.companyId, t.code, t.effectiveAt)]);
export const calendarEvents = sqliteTable('calendar_events', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), title: text('title').notNull(), category: text('category').notNull(), startsAt: integer('starts_at', { mode: 'timestamp_ms' }).notNull(), endsAt: integer('ends_at', { mode: 'timestamp_ms' }), entityType: text('entity_type'), entityId: text('entity_id'), ownerId: text('owner_id').references(() => users.id), status: text('status').notNull().default('scheduled'), ...timestamps }, (t) => [index('idx_calendar_events_company_start').on(t.companyId, t.startsAt)]);
export const emailTemplates = sqliteTable('email_templates', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), subject: text('subject').notNull(), htmlBody: text('html_body').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_email_templates_company_code').on(t.companyId, t.code)]);
