import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const id = (name = 'id') => text(name).primaryKey();
const timestamps = { createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull() };
const moneyColumns = { currency: text('currency', { length: 3 }).notNull().default('UGX'), amountMinor: text('amount_minor').notNull().default('0') };

export const companies = sqliteTable('companies', {
  id: id(), name: text('name').notNull(), countryCode: text('country_code').notNull().default('UG'), baseCurrency: text('base_currency').notNull().default('UGX'), timezone: text('timezone').notNull().default('Africa/Kampala'), ...timestamps,
});
export const users = sqliteTable('users', {
  id: id(),
  companyId: text('company_id').notNull().references(() => companies.id),
  externalIdentityId: text('external_identity_id').notNull(),
  email: text('email').notNull(),
  displayName: text('display_name').notNull(),
  department: text('department'),
  passwordHash: text('password_hash'),
  mustChangePassword: integer('must_change_password', { mode: 'boolean' }).notNull().default(true),
  failedLoginAttempts: integer('failed_login_attempts').notNull().default(0),
  lockedUntil: integer('locked_until', { mode: 'timestamp_ms' }),
  lastLoginAt: integer('last_login_at', { mode: 'timestamp_ms' }),
  passwordChangedAt: integer('password_changed_at', { mode: 'timestamp_ms' }),
  status: text('status').notNull().default('active'),
  ...timestamps,
}, (t) => [
  uniqueIndex('uq_users_company_external').on(t.companyId, t.externalIdentityId),
  uniqueIndex('uq_users_company_email').on(t.companyId, t.email),
]);
export const roles = sqliteTable('roles', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), description: text('description'), readOnly: integer('read_only', { mode: 'boolean' }).notNull().default(false), ...timestamps,
}, (t) => [uniqueIndex('uq_roles_company_name').on(t.companyId, t.name)]);
export const permissions = sqliteTable('permissions', { id: id(), code: text('code').notNull().unique(), description: text('description').notNull() });
export const userRoles = sqliteTable('user_roles', { userId: text('user_id').notNull().references(() => users.id), roleId: text('role_id').notNull().references(() => roles.id), assignedAt: integer('assigned_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [uniqueIndex('uq_user_roles').on(t.userId, t.roleId)]);
export const rolePermissions = sqliteTable('role_permissions', { roleId: text('role_id').notNull().references(() => roles.id), permissionId: text('permission_id').notNull().references(() => permissions.id) }, (t) => [uniqueIndex('uq_role_permissions').on(t.roleId, t.permissionId)]);
export const positions = sqliteTable('positions', { id:id(), companyId:text('company_id').notNull().references(()=>companies.id), name:text('name').notNull(), roleId:text('role_id').notNull().references(()=>roles.id), active:integer('active',{mode:'boolean'}).notNull().default(true), ...timestamps },(t)=>[uniqueIndex('uq_positions_company_name').on(t.companyId,t.name),index('idx_positions_role').on(t.roleId)]);

export const customers = sqliteTable('customers', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), tradingName: text('trading_name'), customerType: text('customer_type').notNull().default('Company'), category: text('category').notNull().default('Other'), industry: text('industry'), tin: text('tin'), vatRegistered: integer('vat_registered', { mode: 'boolean' }).notNull().default(false), registrationNumber: text('registration_number'), website: text('website'), email: text('email'), correspondenceEmail: text('correspondence_email'), phone: text('phone'), secondaryPhone: text('secondary_phone'), country: text('country').notNull().default('Uganda'), district: text('district'), city: text('city'), address: text('address'), postalAddress: text('postal_address'), billingContact: text('billing_contact'), billingEmail: text('billing_email'), preferredCurrency: text('preferred_currency').notNull().default('UGX'), paymentTerms: text('payment_terms').notNull().default('30 days'), dueDays: integer('due_days').notNull().default(30), retentionApplicable: integer('retention_applicable', { mode: 'boolean' }).notNull().default(false), retentionBasisPoints: integer('retention_basis_points').notNull().default(0), creditLimitMinor: text('credit_limit_minor').notNull().default('0'), accountManagerId: text('account_manager_id').references(() => users.id), source: text('source'), firstEngagementAt: integer('first_engagement_at', { mode: 'timestamp_ms' }), notes: text('notes'), tagsJson: text('tags_json'), status: text('status').notNull().default('active'), archivedAt: integer('archived_at', { mode: 'timestamp_ms' }), sourceSystem: text('source_system'), sourceRef: text('source_ref'), sourceImportedAt: integer('source_imported_at', { mode: 'timestamp_ms' }), ...timestamps,
}, (t) => [uniqueIndex('uq_customers_company_code').on(t.companyId, t.code), index('idx_customers_company_name').on(t.companyId, t.name), index('idx_customers_company_status').on(t.companyId, t.status), index('idx_customers_company_tin').on(t.companyId, t.tin), index('idx_customers_company_email').on(t.companyId, t.email)]);
export const suppliers = sqliteTable('suppliers', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), tin: text('tin'), vatRegistered: integer('vat_registered', { mode: 'boolean' }).notNull().default(false), creditTermsDays: integer('credit_terms_days').notNull().default(0), email: text('email'), phone: text('phone'), address: text('address'), fax: text('fax'), sourceSystem: text('source_system'), sourceRef: text('source_ref'), sourceImportedAt: integer('source_imported_at', { mode: 'timestamp_ms' }), status: text('status').notNull().default('active'), ...timestamps,
}, (t) => [uniqueIndex('uq_suppliers_company_code').on(t.companyId, t.code), index('idx_suppliers_company_name').on(t.companyId, t.name)]);

export const bids = sqliteTable('bids', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), title: text('title').notNull(), organization: text('organization').notNull(), description:text('description'), category: text('category'), subcategory:text('subcategory'), source: text('source'), sourceUrl: text('source_url'), location:text('location'), procurementMethod:text('procurement_method'), publishedAt: integer('published_at', { mode: 'timestamp_ms' }), clarificationDeadline:integer('clarification_deadline',{mode:'timestamp_ms'}), preBidMeetingAt:integer('pre_bid_meeting_at',{mode:'timestamp_ms'}), siteVisitAt:integer('site_visit_at',{mode:'timestamp_ms'}), closesAt: integer('closes_at', { mode: 'timestamp_ms' }).notNull(), expectedAwardAt:integer('expected_award_at',{mode:'timestamp_ms'}), currency: text('currency').notNull().default('UGX'), estimatedValueMinor: text('estimated_value_minor'), tenderFeeMinor:text('tender_fee_minor').notNull().default('0'), securityRequired:integer('security_required',{mode:'boolean'}).notNull().default(false), bidValidityDays:integer('bid_validity_days'), eligibilityNotes:text('eligibility_notes'), priority:text('priority').notNull().default('medium'), tagsJson:text('tags_json'), status: text('status').notNull().default('new'), assignedTo: text('assigned_to').references(() => users.id), archivedAt:integer('archived_at',{mode:'timestamp_ms'}), ...timestamps,
}, (t) => [uniqueIndex('uq_bids_company_reference').on(t.companyId, t.reference), index('idx_bids_status_closes').on(t.companyId, t.status, t.closesAt)]);
export const bidRequirements = sqliteTable('bid_requirements', {
  id: id(), bidId: text('bid_id').notNull().references(() => bids.id), requirement: text('requirement').notNull(), description:text('description'), category:text('category').notNull().default('administrative'), required: integer('required', { mode: 'boolean' }).notNull().default(true), ownerId:text('owner_id').references(()=>users.id), dueAt:integer('due_at',{mode:'timestamp_ms'}), status:text('status').notNull().default('not_started'), uploaded: integer('uploaded', { mode: 'boolean' }).notNull().default(false), verified: integer('verified', { mode: 'boolean' }).notNull().default(false), verifiedBy:text('verified_by').references(()=>users.id), verifiedAt:integer('verified_at',{mode:'timestamp_ms'}), supportingDocumentId:text('supporting_document_id').references(()=>documents.id), expiresAt: integer('expires_at', { mode: 'timestamp_ms' }), notes: text('notes'), ...timestamps,
}, (t) => [index('idx_bid_requirements_bid').on(t.bidId)]);
export const bidExpenses = sqliteTable('bid_expenses', {
  id: id(), bidId: text('bid_id').notNull().references(() => bids.id), expenseNumber:text('expense_number').notNull().default('UNASSIGNED'), category: text('category').notNull(), description: text('description').notNull(), supplierPayee:text('supplier_payee'), ...moneyColumns, taxMinor:text('tax_minor').notNull().default('0'), paymentMethod:text('payment_method'), receiptDocumentId:text('receipt_document_id').references(()=>documents.id), approvalStatus:text('approval_status').notNull().default('draft'), accountingStatus:text('accounting_status').notNull().default('unposted'), journalEntryId: text('journal_entry_id'), incurredAt: integer('incurred_at', { mode: 'timestamp_ms' }).notNull(), createdBy: text('created_by').notNull().references(() => users.id), approvedBy:text('approved_by').references(()=>users.id), approvedAt:integer('approved_at',{mode:'timestamp_ms'}), ...timestamps,
}, (t) => [index('idx_bid_expenses_bid').on(t.bidId)]);

export const projectStages = sqliteTable('project_stages', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), sequence: integer('sequence').notNull(), enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true), ...timestamps,
}, (t) => [uniqueIndex('uq_project_stages_company_sequence').on(t.companyId, t.sequence)]);
export const projects = sqliteTable('projects', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), customerId: text('customer_id').notNull().references(() => customers.id), bidId: text('bid_id').references(() => bids.id), category: text('category'), description:text('description'), location: text('location'), priority:text('priority').notNull().default('medium'), contractReference:text('contract_reference'), purchaseOrderReference:text('purchase_order_reference'), contractCurrency: text('contract_currency').notNull().default('UGX'), contractValueMinor: text('contract_value_minor').notNull(), budgetMinor: text('budget_minor').notNull().default('0'), committedMinor:text('committed_minor').notNull().default('0'), retentionBasisPoints: integer('retention_basis_points').notNull().default(500), advanceBasisPoints:integer('advance_basis_points').notNull().default(0), defectsLiabilityMonths:integer('defects_liability_months').notNull().default(6), startsAt: integer('starts_at', { mode: 'timestamp_ms' }), plannedCompletionAt: integer('planned_completion_at', { mode: 'timestamp_ms' }), stageId: text('stage_id').references(() => projectStages.id), status: text('status').notNull().default('active'), health:text('health').notNull().default('on_track'), completionBasisPoints: integer('completion_basis_points').notNull().default(0), projectManagerId: text('project_manager_id').references(() => users.id), siteManagerId:text('site_manager_id').references(()=>users.id), archivedAt:integer('archived_at',{mode:'timestamp_ms'}), ...timestamps,
}, (t) => [uniqueIndex('uq_projects_company_code').on(t.companyId, t.code), index('idx_projects_customer').on(t.customerId), index('idx_projects_bid').on(t.bidId)]);
export const projectTasks = sqliteTable('project_tasks', {
  id: id(), projectId: text('project_id').notNull().references(() => projects.id), milestoneId:text('milestone_id'), title: text('title').notNull(), description:text('description'), assigneeId: text('assignee_id').references(() => users.id), startsAt:integer('starts_at',{mode:'timestamp_ms'}), dueAt: integer('due_at', { mode: 'timestamp_ms' }), status: text('status').notNull().default('not_started'), priority: text('priority').notNull().default('normal'), stage:text('stage'), detailsJson:text('details_json'), completedAt:integer('completed_at',{mode:'timestamp_ms'}), ...timestamps,
}, (t) => [index('idx_project_tasks_project_status').on(t.projectId, t.status)]);

export const procurementRequests = sqliteTable('procurement_requests', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), projectId: text('project_id').references(() => projects.id), bidId: text('bid_id').references(() => bids.id), department: text('department'), purpose: text('purpose').notNull(), currency: text('currency').notNull().default('UGX'), totalMinor: text('total_minor').notNull(), status: text('status').notNull().default('draft'), requestedBy: text('requested_by').notNull().references(() => users.id), ...timestamps,
}, (t) => [uniqueIndex('uq_procurement_requests_reference').on(t.companyId, t.reference), index('idx_procurement_project_status').on(t.projectId, t.status)]);
export const purchaseOrders = sqliteTable('purchase_orders', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), requestId: text('request_id').references(() => procurementRequests.id), supplierId: text('supplier_id').notNull().references(() => suppliers.id), projectId: text('project_id').references(() => projects.id), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull(), taxMinor: text('tax_minor').notNull().default('0'), totalMinor: text('total_minor').notNull(), status: text('status').notNull().default('draft'), ...timestamps,
}, (t) => [uniqueIndex('uq_purchase_orders_reference').on(t.companyId, t.reference), index('idx_purchase_orders_supplier').on(t.supplierId)]);
export const goodsReceipts = sqliteTable('goods_receipts', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), purchaseOrderId: text('purchase_order_id').notNull().references(() => purchaseOrders.id), receivedAt: integer('received_at', { mode: 'timestamp_ms' }).notNull(), receivedBy: text('received_by').notNull().references(() => users.id), status: text('status').notNull().default('received'), notes: text('notes'), ...timestamps,
}, (t) => [uniqueIndex('uq_goods_receipts_reference').on(t.companyId, t.reference)]);

export const warehouses = sqliteTable('warehouses', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), location: text('location'), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_warehouses_company_code').on(t.companyId, t.code)]);
export const inventoryItems = sqliteTable('inventory_items', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), sku: text('sku').notNull(), name: text('name').notNull(), category: text('category').notNull(), unit: text('unit').notNull(), quantityMinor: text('quantity_minor').notNull().default('0'), reservedMinor: text('reserved_minor').notNull().default('0'), reorderLevelMinor: text('reorder_level_minor').notNull().default('0'), averageCostMinor: text('average_cost_minor').notNull().default('0'), currency: text('currency').notNull().default('UGX'), tracksBatch: integer('tracks_batch', { mode: 'boolean' }).notNull().default(false), ...timestamps,
}, (t) => [uniqueIndex('uq_inventory_company_sku').on(t.companyId, t.sku), index('idx_inventory_company_category').on(t.companyId, t.category)]);
export const stockMovements = sqliteTable('stock_movements', {
  id: id(), itemId: text('item_id').notNull().references(() => inventoryItems.id), warehouseId: text('warehouse_id').notNull().references(() => warehouses.id), projectId: text('project_id').references(() => projects.id), goodsReceiptId: text('goods_receipt_id').references(() => goodsReceipts.id), movementType: text('movement_type').notNull(), quantityMinor: text('quantity_minor').notNull(), unitCostMinor: text('unit_cost_minor'), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(), createdBy: text('created_by').notNull().references(() => users.id), ...timestamps,
}, (t) => [index('idx_stock_movements_item_date').on(t.itemId, t.occurredAt), index('idx_stock_movements_project').on(t.projectId)]);

export const invoices = sqliteTable('invoices', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), number: text('number').notNull(), customerId: text('customer_id').notNull().references(() => customers.id), projectId: text('project_id').references(() => projects.id), issueDate: integer('issue_date', { mode: 'timestamp_ms' }).notNull(), dueDate: integer('due_date', { mode: 'timestamp_ms' }).notNull(), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull(), discountMinor: text('discount_minor').notNull().default('0'), taxMinor: text('tax_minor').notNull().default('0'), retentionMinor: text('retention_minor').notNull().default('0'), totalMinor: text('total_minor').notNull(), paidMinor: text('paid_minor').notNull().default('0'), status: text('status').notNull().default('draft'), journalEntryId: text('journal_entry_id'), ...timestamps,
}, (t) => [uniqueIndex('uq_invoices_company_number').on(t.companyId, t.number), index('idx_invoices_customer_due').on(t.customerId, t.dueDate), index('idx_invoices_project').on(t.projectId)]);
export const invoiceLines = sqliteTable('invoice_lines', { id: id(), invoiceId: text('invoice_id').notNull().references(() => invoices.id), description: text('description').notNull(), quantityMinor: text('quantity_minor').notNull(), unitPriceMinor: text('unit_price_minor').notNull(), taxBasisPoints: integer('tax_basis_points').notNull().default(0), lineTotalMinor: text('line_total_minor').notNull(), sequence: integer('sequence').notNull() }, (t) => [index('idx_invoice_lines_invoice').on(t.invoiceId)]);
export const payments = sqliteTable('payments', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), customerId: text('customer_id').references(() => customers.id), supplierId: text('supplier_id').references(() => suppliers.id), projectId: text('project_id').references(() => projects.id), ...moneyColumns, receivedOrPaidAt: integer('received_or_paid_at', { mode: 'timestamp_ms' }).notNull(), method: text('method').notNull(), bankReference: text('bank_reference'), status: text('status').notNull().default('expected'), journalEntryId: text('journal_entry_id'), ...timestamps,
}, (t) => [uniqueIndex('uq_payments_company_reference').on(t.companyId, t.reference), index('idx_payments_customer').on(t.customerId)]);
export const paymentAllocations = sqliteTable('payment_allocations', { id: id(), paymentId: text('payment_id').notNull().references(() => payments.id), invoiceId: text('invoice_id').notNull().references(() => invoices.id), amountMinor: text('amount_minor').notNull(), createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [uniqueIndex('uq_payment_invoice_allocation').on(t.paymentId, t.invoiceId), index('idx_allocations_invoice').on(t.invoiceId)]);
export const supplierBills = sqliteTable('supplier_bills', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), supplierId: text('supplier_id').notNull().references(() => suppliers.id), purchaseOrderId: text('purchase_order_id').references(() => purchaseOrders.id), invoiceNumber: text('invoice_number').notNull(), issueDate: integer('issue_date', { mode: 'timestamp_ms' }).notNull(), dueDate: integer('due_date', { mode: 'timestamp_ms' }).notNull(), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull(), taxMinor: text('tax_minor').notNull().default('0'), totalMinor: text('total_minor').notNull(), paidMinor: text('paid_minor').notNull().default('0'), status: text('status').notNull().default('open'), journalEntryId: text('journal_entry_id'), ...timestamps,
}, (t) => [uniqueIndex('uq_supplier_bills_supplier_number').on(t.supplierId, t.invoiceNumber), index('idx_supplier_bills_due_status').on(t.dueDate, t.status)]);

export const fiscalYears = sqliteTable('fiscal_years', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), startsAt: integer('starts_at', { mode: 'timestamp_ms' }).notNull(), endsAt: integer('ends_at', { mode: 'timestamp_ms' }).notNull(), status: text('status').notNull().default('open'), ...timestamps }, (t) => [uniqueIndex('uq_fiscal_year_company_name').on(t.companyId, t.name)]);
export const accountingPeriods = sqliteTable('accounting_periods', { id: id(), fiscalYearId: text('fiscal_year_id').notNull().references(() => fiscalYears.id), name: text('name').notNull(), startsAt: integer('starts_at', { mode: 'timestamp_ms' }).notNull(), endsAt: integer('ends_at', { mode: 'timestamp_ms' }).notNull(), status: text('status').notNull().default('open'), lockedBy: text('locked_by').references(() => users.id), lockedAt: integer('locked_at', { mode: 'timestamp_ms' }) }, (t) => [uniqueIndex('uq_accounting_period_year_name').on(t.fiscalYearId, t.name)]);
export const accounts = sqliteTable('accounts', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), type: text('type').notNull(), normalBalance: text('normal_balance').notNull(), parentId: text('parent_id'), legacyOpeningBalanceMinor: text('legacy_opening_balance_minor'), legacyOpeningBalanceRaw: text('legacy_opening_balance_raw'), sourceSystem: text('source_system'), sourceRef: text('source_ref'), sourceImportedAt: integer('source_imported_at', { mode: 'timestamp_ms' }), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_accounts_company_code').on(t.companyId, t.code), index('idx_accounts_source_ref').on(t.companyId,t.sourceSystem,t.sourceRef)]);
export const journalEntries = sqliteTable('journal_entries', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), number: text('number').notNull(), periodId: text('period_id').notNull().references(() => accountingPeriods.id), entryDate: integer('entry_date', { mode: 'timestamp_ms' }).notNull(), sourceType: text('source_type').notNull(), sourceId: text('source_id'), memo: text('memo').notNull(), currency: text('currency').notNull().default('UGX'), status: text('status').notNull().default('draft'), reversalOfId: text('reversal_of_id'), createdBy: text('created_by').notNull().references(() => users.id), postedBy: text('posted_by').references(() => users.id), postedAt: integer('posted_at', { mode: 'timestamp_ms' }), ...timestamps,
}, (t) => [uniqueIndex('uq_journal_entries_company_number').on(t.companyId, t.number), uniqueIndex('uq_journal_source_idempotency').on(t.companyId, t.sourceType, t.sourceId), index('idx_journal_entries_period_status').on(t.periodId, t.status)]);
export const journalLines = sqliteTable('journal_lines', { id: id(), journalEntryId: text('journal_entry_id').notNull().references(() => journalEntries.id), accountId: text('account_id').notNull().references(() => accounts.id), description: text('description'), debitMinor: text('debit_minor').notNull().default('0'), creditMinor: text('credit_minor').notNull().default('0'), customerId: text('customer_id').references(() => customers.id), supplierId: text('supplier_id').references(() => suppliers.id), projectId: text('project_id').references(() => projects.id), sequence: integer('sequence').notNull() }, (t) => [index('idx_journal_lines_entry').on(t.journalEntryId), index('idx_journal_lines_account').on(t.accountId)]);

export const bankAccounts = sqliteTable('bank_accounts', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), bankName: text('bank_name').notNull(), accountName: text('account_name').notNull(), maskedNumber: text('masked_number').notNull(), currency: text('currency').notNull().default('UGX'), ledgerAccountId: text('ledger_account_id').notNull().references(() => accounts.id), openingBalanceMinor: text('opening_balance_minor').notNull().default('0'), lastReconciledAt: integer('last_reconciled_at', { mode: 'timestamp_ms' }), ...timestamps });
export const bankTransactions = sqliteTable('bank_transactions', { id: id(), bankAccountId: text('bank_account_id').notNull().references(() => bankAccounts.id), externalId: text('external_id'), transactionDate: integer('transaction_date', { mode: 'timestamp_ms' }).notNull(), description: text('description').notNull(), reference: text('reference'), amountMinor: text('amount_minor').notNull(), status: text('status').notNull().default('unmatched'), journalEntryId: text('journal_entry_id').references(() => journalEntries.id), ...timestamps }, (t) => [uniqueIndex('uq_bank_transaction_external').on(t.bankAccountId, t.externalId), index('idx_bank_transactions_account_date').on(t.bankAccountId, t.transactionDate)]);
export const bankReconciliations = sqliteTable('bank_reconciliations', { id: id(), bankAccountId: text('bank_account_id').notNull().references(() => bankAccounts.id), periodEnd: integer('period_end', { mode: 'timestamp_ms' }).notNull(), statementBalanceMinor: text('statement_balance_minor').notNull(), ledgerBalanceMinor: text('ledger_balance_minor').notNull(), differenceMinor: text('difference_minor').notNull(), status: text('status').notNull().default('draft'), finalizedBy: text('finalized_by').references(() => users.id), finalizedAt: integer('finalized_at', { mode: 'timestamp_ms' }), ...timestamps }, (t) => [uniqueIndex('uq_bank_reconciliation_period').on(t.bankAccountId, t.periodEnd)]);
export const retentions = sqliteTable('retentions', { id: id(), projectId: text('project_id').notNull().references(() => projects.id), invoiceId: text('invoice_id').references(() => invoices.id), basisPoints: integer('basis_points').notNull(), baseMinor: text('base_minor').notNull(), amountMinor: text('amount_minor').notNull(), withheldAt: integer('withheld_at', { mode: 'timestamp_ms' }), expectedReleaseAt: integer('expected_release_at', { mode: 'timestamp_ms' }), actualReleaseAt: integer('actual_release_at', { mode: 'timestamp_ms' }), receivedMinor: text('received_minor').notNull().default('0'), status: text('status').notNull().default('withheld'), ...timestamps }, (t) => [index('idx_retentions_project_status').on(t.projectId, t.status), index('idx_retentions_release').on(t.expectedReleaseAt)]);

export const employees = sqliteTable('employees', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), userId:text('user_id').references(()=>users.id), positionId:text('position_id').references(()=>positions.id), employeeNumber: text('employee_number').notNull(), name: text('name').notNull(), department: text('department'), jobTitle: text('job_title'), email: text('email'), phone: text('phone'), hiredAt: integer('hired_at', { mode: 'timestamp_ms' }), currency: text('currency').notNull().default('UGX'), salaryMinor: text('salary_minor').notNull(), paymentMethod: text('payment_method'), status: text('status').notNull().default('active'), ...timestamps }, (t) => [uniqueIndex('uq_employees_company_number').on(t.companyId, t.employeeNumber),uniqueIndex('uq_employees_user').on(t.userId),index('idx_employees_position').on(t.positionId)]);
export const payrollRuns = sqliteTable('payroll_runs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), periodId: text('period_id').notNull().references(() => accountingPeriods.id), currency: text('currency').notNull().default('UGX'), grossMinor: text('gross_minor').notNull().default('0'), deductionsMinor: text('deductions_minor').notNull().default('0'), netMinor: text('net_minor').notNull().default('0'), status: text('status').notNull().default('draft'), journalEntryId: text('journal_entry_id').references(() => journalEntries.id), ...timestamps }, (t) => [uniqueIndex('uq_payroll_run_period').on(t.companyId, t.periodId)]);

export const documents = sqliteTable('documents', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), internalNumber: text('internal_number').notNull(), storageKey: text('storage_key').notNull(), filename: text('filename').notNull(), originalFilename: text('original_filename').notNull(), mimeType: text('mime_type').notNull(), sizeBytes: integer('size_bytes').notNull(), sha256: text('sha256').notNull(), title: text('title').notNull(), category: text('category').notNull().default('Other'), referenceNumber: text('reference_number'), documentDate: integer('document_date', { mode: 'timestamp_ms' }), description: text('description'), relatedModule: text('related_module'), relatedRecordId: text('related_record_id'), tagsJson: text('tags_json'), notes: text('notes'), ocrRequired: integer('ocr_required', { mode: 'boolean' }).notNull().default(false), rawOcrText: text('raw_ocr_text'), uploadedBy: text('uploaded_by').notNull().references(() => users.id), ocrStatus: text('ocr_status').notNull().default('uploaded'), verificationStatus: text('verification_status').notNull().default('pending'), archivedAt: integer('archived_at', { mode: 'timestamp_ms' }), ...timestamps,
}, (t) => [uniqueIndex('uq_documents_storage_key').on(t.storageKey), uniqueIndex('uq_documents_company_number').on(t.companyId, t.internalNumber), index('idx_documents_company_ocr').on(t.companyId, t.ocrStatus), index('idx_documents_company_category').on(t.companyId, t.category), index('idx_documents_company_hash').on(t.companyId, t.sha256)]);
export const documentLinks = sqliteTable('document_links', { id: id(), documentId: text('document_id').notNull().references(() => documents.id), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), relationship: text('relationship').notNull(), createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [uniqueIndex('uq_document_links').on(t.documentId, t.entityType, t.entityId, t.relationship), index('idx_document_links_entity').on(t.entityType, t.entityId)]);
export const ocrJobs = sqliteTable('ocr_jobs', { id: id(), documentId: text('document_id').notNull().references(() => documents.id), provider: text('provider').notNull(), providerMode: text('provider_mode').notNull().default('development'), status: text('status').notNull().default('queued'), documentType: text('document_type'), extractedJson: text('extracted_json'), rawText: text('raw_text'), warningsJson: text('warnings_json'), confidenceBasisPoints: integer('confidence_basis_points'), errorCode: text('error_code'), errorMessage: text('error_message'), attempts: integer('attempts').notNull().default(0), completedAt: integer('completed_at', { mode: 'timestamp_ms' }), ...timestamps }, (t) => [index('idx_ocr_jobs_document').on(t.documentId), index('idx_ocr_jobs_status').on(t.status)]);
export const receiptRecords = sqliteTable('receipt_records', {
  id: id(), companyId: text('company_id').notNull().references(() => companies.id), internalNumber: text('internal_number').notNull(), documentId: text('document_id').notNull().references(() => documents.id), supplierId: text('supplier_id').references(() => suppliers.id), supplierNameRaw: text('supplier_name_raw'), supplierTin: text('supplier_tin'), businessAddress: text('business_address'), telephone: text('telephone'), receiptNumber: text('receipt_number'), invoiceNumber: text('invoice_number'), receiptDate: integer('receipt_date', { mode: 'timestamp_ms' }), receiptTime: text('receipt_time'), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull().default('0'), discountMinor: text('discount_minor').notNull().default('0'), vatAmountMinor: text('vat_amount_minor').notNull().default('0'), vatRateBasisPoints: integer('vat_rate_basis_points'), vatTreatment: text('vat_treatment').notNull().default('unknown'), otherTaxMinor: text('other_tax_minor').notNull().default('0'), totalMinor: text('total_minor').notNull().default('0'), amountPaidMinor: text('amount_paid_minor').notNull().default('0'), changeMinor: text('change_minor').notNull().default('0'), paymentMethod: text('payment_method'), transactionReference: text('transaction_reference'), cashier: text('cashier'), customerName: text('customer_name'), notes: text('notes'), ocrSnapshotJson: text('ocr_snapshot_json'), status: text('status').notNull().default('confirmed'), reviewedBy: text('reviewed_by').notNull().references(() => users.id), reviewedAt: integer('reviewed_at', { mode: 'timestamp_ms' }).notNull(), ...timestamps,
}, (t) => [uniqueIndex('uq_receipts_company_number').on(t.companyId, t.internalNumber), uniqueIndex('uq_receipts_document').on(t.documentId), index('idx_receipts_duplicate').on(t.companyId, t.receiptNumber, t.receiptDate, t.totalMinor), index('idx_receipts_supplier').on(t.supplierId)]);
export const receiptLineItems = sqliteTable('receipt_line_items', { id: id(), receiptId: text('receipt_id').notNull().references(() => receiptRecords.id), description: text('description').notNull(), quantityMinor: text('quantity_minor').notNull().default('1000'), unit: text('unit'), unitPriceMinor: text('unit_price_minor').notNull().default('0'), taxMinor: text('tax_minor').notNull().default('0'), lineTotalMinor: text('line_total_minor').notNull().default('0'), sequence: integer('sequence').notNull() }, (t) => [index('idx_receipt_lines_receipt').on(t.receiptId)]);
export const documentFieldCorrections = sqliteTable('document_field_corrections', { id: id(), documentId: text('document_id').notNull().references(() => documents.id), fieldName: text('field_name').notNull(), ocrValue: text('ocr_value'), confirmedValue: text('confirmed_value'), correctedBy: text('corrected_by').notNull().references(() => users.id), correctedAt: integer('corrected_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [index('idx_document_corrections_document').on(t.documentId)]);

export const approvalRequests = sqliteTable('approval_requests', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), amountMinor: text('amount_minor'), currency: text('currency'), status: text('status').notNull().default('pending'), currentStep: integer('current_step').notNull().default(1), requestedBy: text('requested_by').notNull().references(() => users.id), ...timestamps }, (t) => [index('idx_approvals_entity').on(t.entityType, t.entityId), index('idx_approvals_company_status').on(t.companyId, t.status)]);
export const approvalSteps = sqliteTable('approval_steps', { id: id(), requestId: text('request_id').notNull().references(() => approvalRequests.id), sequence: integer('sequence').notNull(), roleId: text('role_id').references(() => roles.id), approverId: text('approver_id').references(() => users.id), status: text('status').notNull().default('pending'), decisionNote: text('decision_note'), decidedAt: integer('decided_at', { mode: 'timestamp_ms' }) }, (t) => [uniqueIndex('uq_approval_step_sequence').on(t.requestId, t.sequence)]);
export const notifications = sqliteTable('notifications', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), userId: text('user_id').references(() => users.id), type: text('type').notNull(), title: text('title').notNull(), message: text('message').notNull(), entityType: text('entity_type'), entityId: text('entity_id'), priority: text('priority').notNull().default('normal'), readAt: integer('read_at', { mode: 'timestamp_ms' }), createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [index('idx_notifications_user_read').on(t.userId, t.readAt)]);
export const auditLogs = sqliteTable('audit_logs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), userId: text('user_id').references(() => users.id), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), oldValueJson: text('old_value_json'), newValueJson: text('new_value_json'), requestId: text('request_id'), ipHash: text('ip_hash'), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [index('idx_audit_entity_date').on(t.entityType, t.entityId, t.occurredAt), index('idx_audit_company_date').on(t.companyId, t.occurredAt)]);

export const authSessions = sqliteTable('auth_sessions', {
  id: id(),
  companyId: text('company_id').notNull().references(() => companies.id),
  userId: text('user_id').notNull().references(() => users.id),
  tokenHash: text('token_hash').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  lastSeenAt: integer('last_seen_at', { mode: 'timestamp_ms' }).notNull(),
  revokedAt: integer('revoked_at', { mode: 'timestamp_ms' }),
  ipHash: text('ip_hash'),
  userAgentHash: text('user_agent_hash'),
  ...timestamps,
}, (t) => [uniqueIndex('uq_auth_sessions_token_hash').on(t.tokenHash), index('idx_auth_sessions_user_expiry').on(t.userId,t.expiresAt)]);

export const rateLimitBuckets = sqliteTable('rate_limit_buckets', {
  id: id(),
  keyHash: text('key_hash').notNull(),
  action: text('action').notNull(),
  windowStart: integer('window_start', { mode: 'timestamp_ms' }).notNull(),
  count: integer('count').notNull().default(0),
  blockedUntil: integer('blocked_until', { mode: 'timestamp_ms' }),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (t) => [uniqueIndex('uq_rate_limit_key_action').on(t.keyHash,t.action), index('idx_rate_limit_blocked').on(t.blockedUntil)]);

export const securityEvents = sqliteTable('security_events', {
  id: id(),
  companyId: text('company_id'),
  userId: text('user_id'),
  eventType: text('event_type').notNull(),
  severity: text('severity').notNull().default('info'),
  route: text('route'),
  method: text('method'),
  requestId: text('request_id'),
  ipHash: text('ip_hash'),
  userAgentHash: text('user_agent_hash'),
  detailsJson: text('details_json'),
  occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(),
  resolvedAt: integer('resolved_at', { mode: 'timestamp_ms' }),
}, (t) => [index('idx_security_events_date').on(t.occurredAt), index('idx_security_events_type').on(t.eventType,t.occurredAt)]);

export const dataImportBatches = sqliteTable('data_import_batches', {
  id: id(),
  companyId: text('company_id').notNull().references(() => companies.id),
  sourceSystem: text('source_system').notNull(),
  sourceFileName: text('source_file_name').notNull(),
  sourceExportDate: text('source_export_date'),
  sourceExportTimestamp: text('source_export_timestamp'),
  status: text('status').notNull().default('pending'),
  recordCountsJson: text('record_counts_json'),
  notes: text('notes'),
  startedAt: integer('started_at', { mode: 'timestamp_ms' }).notNull(),
  completedAt: integer('completed_at', { mode: 'timestamp_ms' }),
}, (t) => [index('idx_import_batches_company_date').on(t.companyId,t.startedAt)]);

export const recordProvenance = sqliteTable('record_provenance', {
  id: id(),
  batchId: text('batch_id').notNull().references(() => dataImportBatches.id),
  entityType: text('entity_type').notNull(),
  entityId: text('entity_id').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRef: text('source_ref'),
  sourceSnapshotJson: text('source_snapshot_json').notNull(),
  importedAt: integer('imported_at', { mode: 'timestamp_ms' }).notNull(),
}, (t) => [uniqueIndex('uq_record_provenance_entity_batch').on(t.batchId,t.entityType,t.entityId), index('idx_record_provenance_source').on(t.sourceRecordType,t.sourceRef)]);

export const catalogItems = sqliteTable('catalog_items', {
  id: id(),
  companyId: text('company_id').notNull().references(() => companies.id),
  name: text('name').notNull(),
  itemType: text('item_type').notNull(),
  incomeAccountName: text('income_account_name'),
  description: text('description'),
  priceText: text('price_text'),
  costText: text('cost_text'),
  taxable: integer('taxable', { mode: 'boolean' }).notNull().default(false),
  taxCode: text('tax_code'),
  taxVendor: text('tax_vendor'),
  preferredVendor: text('preferred_vendor'),
  sourceSystem: text('source_system').notNull(),
  sourceRef: text('source_ref').notNull(),
  sourceImportedAt: integer('source_imported_at', { mode: 'timestamp_ms' }).notNull(),
  active: integer('active', { mode: 'boolean' }).notNull().default(true),
  ...timestamps,
}, (t) => [uniqueIndex('uq_catalog_source_ref').on(t.companyId,t.sourceSystem,t.sourceRef), index('idx_catalog_name').on(t.companyId,t.name)]);

export const legacyReferenceValues = sqliteTable('legacy_reference_values', {
  id: id(),
  companyId: text('company_id').notNull().references(() => companies.id),
  category: text('category').notNull(),
  label: text('label').notNull(),
  sourceRef: text('source_ref').notNull(),
  metadataJson: text('metadata_json'),
  sourceSystem: text('source_system').notNull().default('QuickBooks'),
  importedAt: integer('imported_at', { mode: 'timestamp_ms' }).notNull(),
}, (t) => [uniqueIndex('uq_legacy_reference_value').on(t.companyId,t.category,t.sourceRef)]);
export const emailLogs = sqliteTable('email_logs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), provider: text('provider').notNull(), mode: text('mode').notNull(), recipient: text('recipient').notNull(), subject: text('subject').notNull(), entityType: text('entity_type'), entityId: text('entity_id'), status: text('status').notNull(), providerMessageId: text('provider_message_id'), errorCode: text('error_code'), sentBy: text('sent_by').references(() => users.id), ...timestamps }, (t) => [index('idx_email_logs_entity').on(t.entityType, t.entityId)]);
export const backupJobs = sqliteTable('backup_jobs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), type: text('type').notNull(), provider: text('provider').notNull(), status: text('status').notNull(), sizeBytes: integer('size_bytes'), storageDestination: text('storage_destination'), restorePoint: text('restore_point'), verificationStatus: text('verification_status').notNull().default('pending'), requestedBy: text('requested_by').references(() => users.id), ...timestamps });
export const migrationJobs = sqliteTable('migration_jobs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), sourceType: text('source_type').notNull(), status: text('status').notNull().default('uploaded'), sourceDocumentId: text('source_document_id').references(() => documents.id), importedCount: integer('imported_count').notNull().default(0), errorCount: integer('error_count').notNull().default(0), reconciliationJson: text('reconciliation_json'), createdBy: text('created_by').notNull().references(() => users.id), ...timestamps });

// Supporting topology: these tables keep the less frequent workflows relational
// without coupling their rules to UI components or external providers.
export const companySettings = sqliteTable('company_settings', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), key: text('key').notNull(), valueJson: text('value_json').notNull(), updatedBy: text('updated_by').references(() => users.id), ...timestamps }, (t) => [uniqueIndex('uq_company_settings_key').on(t.companyId, t.key)]);
export const departments = sqliteTable('departments', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_departments_company_code').on(t.companyId, t.code)]);
export const businessCategories = sqliteTable('business_categories', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), name: text('name').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_business_categories_code').on(t.companyId, t.code)]);
export const customerContacts = sqliteTable('customer_contacts', { id: id(), customerId: text('customer_id').notNull().references(() => customers.id), title: text('title'), firstName: text('first_name'), lastName: text('last_name'), name: text('name').notNull(), email: text('email'), phone: text('phone'), alternativePhone: text('alternative_phone'), whatsapp: text('whatsapp'), jobTitle: text('job_title'), department: text('department'), preferredChannel: text('preferred_channel'), contactType: text('contact_type').notNull().default('Other'), decisionMaker: integer('decision_maker', { mode: 'boolean' }).notNull().default(false), billing: integer('billing_contact', { mode: 'boolean' }).notNull().default(false), primary: integer('primary_contact', { mode: 'boolean' }).notNull().default(false), notes: text('notes'), status: text('status').notNull().default('active'), archivedAt: integer('archived_at', { mode: 'timestamp_ms' }), ...timestamps }, (t) => [index('idx_customer_contacts_customer').on(t.customerId), index('idx_customer_contacts_email').on(t.email)]);
export const customerCommunications = sqliteTable('customer_communications', { id: id(), customerId: text('customer_id').notNull().references(() => customers.id), contactId: text('contact_id').references(() => customerContacts.id), type: text('type').notNull(), direction: text('direction').notNull(), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(), subject: text('subject').notNull(), summary: text('summary').notNull(), outcome: text('outcome'), nextAction: text('next_action'), followUpAt: integer('follow_up_at', { mode: 'timestamp_ms' }), projectId: text('project_id').references(() => projects.id), bidId: text('bid_id').references(() => bids.id), invoiceId: text('invoice_id').references(() => invoices.id), recordedBy: text('recorded_by').notNull().references(() => users.id), ...timestamps }, (t) => [index('idx_customer_communications_date').on(t.customerId, t.occurredAt), index('idx_customer_communications_followup').on(t.followUpAt)]);
export const customerNotes = sqliteTable('customer_notes', { id: id(), customerId: text('customer_id').notNull().references(() => customers.id), note: text('note').notNull(), pinned: integer('pinned', { mode: 'boolean' }).notNull().default(false), visibility: text('visibility').notNull().default('internal'), authorId: text('author_id').notNull().references(() => users.id), ...timestamps }, (t) => [index('idx_customer_notes_customer').on(t.customerId, t.pinned)]);
export const customerStatements = sqliteTable('customer_statements', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), statementNumber: text('statement_number').notNull(), customerId: text('customer_id').notNull().references(() => customers.id), periodFrom: integer('period_from', { mode: 'timestamp_ms' }).notNull(), periodTo: integer('period_to', { mode: 'timestamp_ms' }).notNull(), currency: text('currency').notNull(), openingBalanceMinor: text('opening_balance_minor').notNull(), closingBalanceMinor: text('closing_balance_minor').notNull(), overdueBalanceMinor: text('overdue_balance_minor').notNull(), retentionOutstandingMinor: text('retention_outstanding_minor').notNull(), optionsJson: text('options_json'), generatedBy: text('generated_by').notNull().references(() => users.id), generatedAt: integer('generated_at', { mode: 'timestamp_ms' }).notNull(), sentTo: text('sent_to'), sentAt: integer('sent_at', { mode: 'timestamp_ms' }), createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [uniqueIndex('uq_customer_statement_number').on(t.companyId, t.statementNumber), index('idx_customer_statements_customer').on(t.customerId, t.generatedAt)]);
export const customerStatementLines = sqliteTable('customer_statement_lines', { id: id(), statementId: text('statement_id').notNull().references(() => customerStatements.id), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(), reference: text('reference').notNull(), description: text('description').notNull(), debitMinor: text('debit_minor').notNull().default('0'), creditMinor: text('credit_minor').notNull().default('0'), balanceMinor: text('balance_minor').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), sequence: integer('sequence').notNull() }, (t) => [index('idx_customer_statement_lines').on(t.statementId, t.sequence)]);
export const customerActivities = sqliteTable('customer_activities', { id: id(), customerId: text('customer_id').notNull().references(() => customers.id), actorId: text('actor_id').references(() => users.id), action: text('action').notNull(), summary: text('summary').notNull(), entityType: text('entity_type'), entityId: text('entity_id'), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull() }, (t) => [index('idx_customer_activity_date').on(t.customerId, t.occurredAt)]);
export const supplierContacts = sqliteTable('supplier_contacts', { id: id(), supplierId: text('supplier_id').notNull().references(() => suppliers.id), name: text('name').notNull(), email: text('email'), phone: text('phone'), jobTitle: text('job_title'), primary: integer('primary_contact', { mode: 'boolean' }).notNull().default(false), ...timestamps }, (t) => [index('idx_supplier_contacts_supplier').on(t.supplierId)]);
export const bidSources = sqliteTable('bid_sources', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), providerType: text('provider_type').notNull(), configurationJson: text('configuration_json'), enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true), lastRunAt: integer('last_run_at', { mode: 'timestamp_ms' }), ...timestamps }, (t) => [uniqueIndex('uq_bid_sources_company_name').on(t.companyId, t.name)]);
export const bidQualifications = sqliteTable('bid_qualifications', { id:id(), bidId:text('bid_id').notNull().references(()=>bids.id), scoreBasisPoints:integer('score_basis_points').notNull().default(0), recommendation:text('recommendation').notNull().default('review'), status:text('status').notNull().default('draft'), decision:text('decision'), decisionReason:text('decision_reason'), preparedBy:text('prepared_by').references(()=>users.id), decidedBy:text('decided_by').references(()=>users.id), decidedAt:integer('decided_at',{mode:'timestamp_ms'}), ...timestamps },(t)=>[uniqueIndex('uq_bid_qualification').on(t.bidId),index('idx_bid_qualification_score').on(t.scoreBasisPoints)]);
export const bidQualificationCriteria = sqliteTable('bid_qualification_criteria',{id:id(),qualificationId:text('qualification_id').notNull().references(()=>bidQualifications.id),criterion:text('criterion').notNull(),weightBasisPoints:integer('weight_basis_points').notNull(),scoreBasisPoints:integer('score_basis_points').notNull(),notes:text('notes'),sequence:integer('sequence').notNull()},(t)=>[uniqueIndex('uq_bid_qualification_criterion').on(t.qualificationId,t.criterion)]);
export const bidDocumentVersions = sqliteTable('bid_document_versions',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),documentId:text('document_id').notNull().references(()=>documents.id),documentType:text('document_type').notNull(),version:integer('version').notNull().default(1),requirementId:text('requirement_id').references(()=>bidRequirements.id),expiresAt:integer('expires_at',{mode:'timestamp_ms'}),verificationStatus:text('verification_status').notNull().default('pending'),notes:text('notes'),replacesVersionId:text('replaces_version_id'),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[uniqueIndex('uq_bid_document_version').on(t.bidId,t.documentType,t.version),index('idx_bid_documents_expiry').on(t.bidId,t.expiresAt)]);
export const bidTeamMembers = sqliteTable('bid_team_members',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),userId:text('user_id').notNull().references(()=>users.id),role:text('role').notNull(),responsibility:text('responsibility'),assignedAt:integer('assigned_at',{mode:'timestamp_ms'}).notNull(),assignedBy:text('assigned_by').notNull().references(()=>users.id)},(t)=>[uniqueIndex('uq_bid_team_member_role').on(t.bidId,t.userId,t.role)]);
export const bidTasks = sqliteTable('bid_tasks',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),requirementId:text('requirement_id').references(()=>bidRequirements.id),title:text('title').notNull(),ownerId:text('owner_id').references(()=>users.id),dueAt:integer('due_at',{mode:'timestamp_ms'}),priority:text('priority').notNull().default('normal'),status:text('status').notNull().default('not_started'),notes:text('notes'),...timestamps},(t)=>[index('idx_bid_tasks_due_status').on(t.bidId,t.status,t.dueAt)]);
export const bidPricingSheets = sqliteTable('bid_pricing_sheets',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),name:text('name').notNull(),version:integer('version').notNull().default(1),currency:text('currency').notNull().default('UGX'),directCostMinor:text('direct_cost_minor').notNull().default('0'),indirectCostMinor:text('indirect_cost_minor').notNull().default('0'),contingencyMinor:text('contingency_minor').notNull().default('0'),taxMinor:text('tax_minor').notNull().default('0'),bidPriceMinor:text('bid_price_minor').notNull().default('0'),expectedProfitMinor:text('expected_profit_minor').notNull().default('0'),status:text('status').notNull().default('draft'),...timestamps},(t)=>[uniqueIndex('uq_bid_pricing_version').on(t.bidId,t.version)]);
export const bidPricingLines = sqliteTable('bid_pricing_lines',{id:id(),sheetId:text('sheet_id').notNull().references(()=>bidPricingSheets.id),description:text('description').notNull(),unit:text('unit').notNull(),quantityThousandths:text('quantity_thousandths').notNull(),unitCostMinor:text('unit_cost_minor').notNull(),markupBasisPoints:integer('markup_basis_points').notNull().default(0),sellingUnitMinor:text('selling_unit_minor').notNull(),taxBasisPoints:integer('tax_basis_points').notNull().default(0),lineTotalMinor:text('line_total_minor').notNull(),supplierSource:text('supplier_source'),sequence:integer('sequence').notNull()},(t)=>[index('idx_bid_pricing_lines_sheet').on(t.sheetId,t.sequence)]);
export const bidBudgets = sqliteTable('bid_budgets',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),category:text('category').notNull(),currency:text('currency').notNull().default('UGX'),budgetMinor:text('budget_minor').notNull(),actualMinor:text('actual_minor').notNull().default('0'),...timestamps},(t)=>[uniqueIndex('uq_bid_budget_category').on(t.bidId,t.category)]);
export const bidSecurities = sqliteTable('bid_securities',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),type:text('type').notNull(),issuer:text('issuer'),securityNumber:text('security_number'),amountMinor:text('amount_minor').notNull().default('0'),currency:text('currency').notNull().default('UGX'),issueDate:integer('issue_date',{mode:'timestamp_ms'}),expiryDate:integer('expiry_date',{mode:'timestamp_ms'}),validityDays:integer('validity_days'),beneficiary:text('beneficiary'),documentId:text('document_id').references(()=>documents.id),feeMinor:text('fee_minor').notNull().default('0'),status:text('status').notNull().default('required'),returnExpectedAt:integer('return_expected_at',{mode:'timestamp_ms'}),returnedAt:integer('returned_at',{mode:'timestamp_ms'}),...timestamps},(t)=>[index('idx_bid_security_expiry').on(t.status,t.expiryDate),index('idx_bid_security_bid').on(t.bidId)]);
export const bidClarifications = sqliteTable('bid_clarifications',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),question:text('question').notNull(),raisedAt:integer('raised_at',{mode:'timestamp_ms'}).notNull(),raisedBy:text('raised_by').notNull().references(()=>users.id),sentTo:text('sent_to'),response:text('response'),responseAt:integer('response_at',{mode:'timestamp_ms'}),documentId:text('document_id').references(()=>documents.id),status:text('status').notNull().default('open'),...timestamps},(t)=>[index('idx_bid_clarifications_status').on(t.bidId,t.status)]);
export const bidAddenda = sqliteTable('bid_addenda',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),addendumNumber:text('addendum_number').notNull(),issuedAt:integer('issued_at',{mode:'timestamp_ms'}).notNull(),summary:text('summary').notNull(),documentId:text('document_id').references(()=>documents.id),impactDeadline:integer('impact_deadline',{mode:'boolean'}).notNull().default(false),impactPricing:integer('impact_pricing',{mode:'boolean'}).notNull().default(false),impactTechnical:integer('impact_technical',{mode:'boolean'}).notNull().default(false),impactRequirements:integer('impact_requirements',{mode:'boolean'}).notNull().default(false),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[uniqueIndex('uq_bid_addendum_number').on(t.bidId,t.addendumNumber)]);
export const bidApprovals = sqliteTable('bid_approvals',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),type:text('type').notNull(),approverId:text('approver_id').references(()=>users.id),decision:text('decision').notNull().default('pending'),comments:text('comments'),decidedAt:integer('decided_at',{mode:'timestamp_ms'}),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[index('idx_bid_approvals_pending').on(t.bidId,t.type,t.decision)]);
export const bidSubmissions = sqliteTable('bid_submissions',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),method:text('method').notNull(),destination:text('destination'),submittedAt:integer('submitted_at',{mode:'timestamp_ms'}).notNull(),submittedBy:text('submitted_by').notNull().references(()=>users.id),referenceNumber:text('reference_number'),receiptDocumentId:text('receipt_document_id').references(()=>documents.id),packageManifestJson:text('package_manifest_json').notNull(),notes:text('notes'),status:text('status').notNull().default('submitted'),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[index('idx_bid_submissions_bid_date').on(t.bidId,t.submittedAt)]);
export const bidResults = sqliteTable('bid_results',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),result:text('result').notNull(),decisionDate:integer('decision_date',{mode:'timestamp_ms'}).notNull(),awardValueMinor:text('award_value_minor'),currency:text('currency').notNull().default('UGX'),awardReference:text('award_reference'),awardDocumentId:text('award_document_id').references(()=>documents.id),evaluationScoreBasisPoints:integer('evaluation_score_basis_points'),technicalScoreBasisPoints:integer('technical_score_basis_points'),financialScoreBasisPoints:integer('financial_score_basis_points'),lossReason:text('loss_reason'),competitorInformation:text('competitor_information'),lessonsLearned:text('lessons_learned'),recordedBy:text('recorded_by').notNull().references(()=>users.id),...timestamps},(t)=>[uniqueIndex('uq_bid_result').on(t.bidId)]);
export const bidNotes = sqliteTable('bid_notes',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),authorId:text('author_id').notNull().references(()=>users.id),note:text('note').notNull(),pinned:integer('pinned',{mode:'boolean'}).notNull().default(false),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[index('idx_bid_notes_bid_date').on(t.bidId,t.createdAt)]);
export const bidCommunications = sqliteTable('bid_communications',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),type:text('type').notNull(),occurredAt:integer('occurred_at',{mode:'timestamp_ms'}).notNull(),contact:text('contact'),subject:text('subject').notNull(),summary:text('summary').notNull(),documentId:text('document_id').references(()=>documents.id),userId:text('user_id').notNull().references(()=>users.id),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[index('idx_bid_communications_bid_date').on(t.bidId,t.occurredAt)]);
export const bidWatches = sqliteTable('bid_watches',{bidId:text('bid_id').notNull().references(()=>bids.id),userId:text('user_id').notNull().references(()=>users.id),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[uniqueIndex('uq_bid_watch').on(t.bidId,t.userId)]);
export const bidActivities = sqliteTable('bid_activities',{id:id(),bidId:text('bid_id').notNull().references(()=>bids.id),actorId:text('actor_id').references(()=>users.id),action:text('action').notNull(),linkedEntityType:text('linked_entity_type'),linkedEntityId:text('linked_entity_id'),summary:text('summary').notNull(),occurredAt:integer('occurred_at',{mode:'timestamp_ms'}).notNull()},(t)=>[index('idx_bid_activity_timeline').on(t.bidId,t.occurredAt)]);
export const bidImportJobs = sqliteTable('bid_import_jobs',{id:id(),companyId:text('company_id').notNull().references(()=>companies.id),provider:text('provider').notNull(),filename:text('filename'),status:text('status').notNull().default('uploaded'),mappingJson:text('mapping_json'),insertedCount:integer('inserted_count').notNull().default(0),skippedCount:integer('skipped_count').notNull().default(0),duplicateCount:integer('duplicate_count').notNull().default(0),errorCount:integer('error_count').notNull().default(0),errorSummaryJson:text('error_summary_json'),createdBy:text('created_by').notNull().references(()=>users.id),...timestamps},(t)=>[index('idx_bid_import_jobs_company').on(t.companyId,t.createdAt)]);
export const projectMilestones = sqliteTable('project_milestones', { id: id(), projectId: text('project_id').notNull().references(() => projects.id), name: text('name').notNull(), description:text('description'), stage:text('stage'), ownerId:text('owner_id').references(()=>users.id), plannedStartAt:integer('planned_start_at',{mode:'timestamp_ms'}), weightBasisPoints:integer('weight_basis_points').notNull().default(0), dueAt: integer('due_at', { mode: 'timestamp_ms' }), priority:text('priority').notNull().default('normal'), deliverable:text('deliverable'), evidenceRequired:integer('evidence_required',{mode:'boolean'}).notNull().default(false), approvalRequired:integer('approval_required',{mode:'boolean'}).notNull().default(false), detailsJson:text('details_json'), completedAt: integer('completed_at', { mode: 'timestamp_ms' }), approvedBy:text('approved_by').references(()=>users.id), approvedAt:integer('approved_at',{mode:'timestamp_ms'}), status: text('status').notNull().default('not_started'), certificateDocumentId: text('certificate_document_id').references(() => documents.id), ...timestamps }, (t) => [index('idx_project_milestones_due').on(t.projectId, t.dueAt)]);
export const projectExpenses = sqliteTable('project_expenses', { id: id(), projectId: text('project_id').notNull().references(() => projects.id), expenseNumber:text('expense_number').notNull(), supplierId: text('supplier_id').references(() => suppliers.id), payee:text('payee'), category: text('category').notNull(), description: text('description').notNull(), currency: text('currency').notNull().default('UGX'), amountMinor: text('amount_minor').notNull(), taxMinor:text('tax_minor').notNull().default('0'), totalMinor:text('total_minor').notNull().default('0'), paymentMethod:text('payment_method'), referenceNumber:text('reference_number'), activity:text('activity'), detailsJson:text('details_json'), receiptDocumentId:text('receipt_document_id').references(()=>documents.id), status:text('status').notNull().default('draft'), occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(), recordedBy:text('recorded_by').notNull().references(()=>users.id), approvedBy:text('approved_by').references(()=>users.id), journalEntryId: text('journal_entry_id').references(() => journalEntries.id), ...timestamps }, (t) => [uniqueIndex('uq_project_expense_number').on(t.projectId,t.expenseNumber),index('idx_project_expenses_project_date').on(t.projectId, t.occurredAt)]);
export const projectBudgetLines=sqliteTable('project_budget_lines',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),category:text('category').notNull(),subcategory:text('subcategory'),description:text('description'),quantityMinor:text('quantity_minor').notNull().default('1000'),unit:text('unit'),unitCostMinor:text('unit_cost_minor').notNull().default('0'),originalMinor:text('original_minor').notNull().default('0'),changesMinor:text('changes_minor').notNull().default('0'),contingencyMinor:text('contingency_minor').notNull().default('0'),committedMinor:text('committed_minor').notNull().default('0'),actualMinor:text('actual_minor').notNull().default('0'),notes:text('notes'),...timestamps},(t)=>[index('idx_project_budget_category').on(t.projectId,t.category)]);
export const projectProgressUpdates=sqliteTable('project_progress_updates',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),previousBasisPoints:integer('previous_basis_points').notNull(),newBasisPoints:integer('new_basis_points').notNull(),stage:text('stage'),workCompleted:text('work_completed'),reason:text('reason'),comment:text('comment').notNull(),evidenceDocumentId:text('evidence_document_id').references(()=>documents.id),updatedBy:text('updated_by').notNull().references(()=>users.id),occurredAt:integer('occurred_at',{mode:'timestamp_ms'}).notNull()},(t)=>[index('idx_project_progress_date').on(t.projectId,t.occurredAt)]);
export const projectWorkActivities=sqliteTable('project_work_activities',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),stage:text('stage').notNull(),title:text('title').notNull(),description:text('description'),startsAt:integer('starts_at',{mode:'timestamp_ms'}),endsAt:integer('ends_at',{mode:'timestamp_ms'}),responsibleId:text('responsible_id').references(()=>users.id),weightBasisPoints:integer('weight_basis_points').notNull().default(0),progressBasisPoints:integer('progress_basis_points').notNull().default(0),status:text('status').notNull().default('not_started'),detailsJson:text('details_json'),...timestamps},(t)=>[index('idx_project_work_stage').on(t.projectId,t.stage)]);
export const projectSiteUpdates=sqliteTable('project_site_updates',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),reportDate:integer('report_date',{mode:'timestamp_ms'}).notNull(),location:text('location'),weather:text('weather'),workCompleted:text('work_completed').notNull(),workInProgress:text('work_in_progress'),workersOnSite:integer('workers_on_site').notNull().default(0),materialsReceived:text('materials_received'),materialsUsed:text('materials_used'),equipmentUsed:text('equipment_used'),delays:text('delays'),issues:text('issues'),instructions:text('instructions'),safetyObservations:text('safety_observations'),visitors:text('visitors'),detailsJson:text('details_json'),photoDocumentId:text('photo_document_id').references(()=>documents.id),notes:text('notes'),createdBy:text('created_by').notNull().references(()=>users.id),...timestamps},(t)=>[index('idx_project_site_updates_date').on(t.projectId,t.reportDate)]);
export const projectTeamMembers=sqliteTable('project_team_members',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),userId:text('user_id').notNull().references(()=>users.id),projectRole:text('project_role').notNull(),responsibility:text('responsibility'),startsAt:integer('starts_at',{mode:'timestamp_ms'}),endsAt:integer('ends_at',{mode:'timestamp_ms'}),allocationBasisPoints:integer('allocation_basis_points').notNull().default(10000),accessLevel:text('access_level'),status:text('status').notNull().default('active'),detailsJson:text('details_json'),...timestamps},(t)=>[uniqueIndex('uq_project_team_member').on(t.projectId,t.userId,t.projectRole)]);
export const projectMaterialRequests=sqliteTable('project_material_requests',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),reference:text('reference').notNull(),material:text('material').notNull(),quantityMinor:text('quantity_minor').notNull(),unit:text('unit').notNull(),requiredAt:integer('required_at',{mode:'timestamp_ms'}),purpose:text('purpose').notNull(),priority:text('priority').notNull().default('normal'),estimatedTotalMinor:text('estimated_total_minor').notNull().default('0'),detailsJson:text('details_json'),supportingDocumentId:text('supporting_document_id').references(()=>documents.id),notes:text('notes'),status:text('status').notNull().default('draft'),requestedBy:text('requested_by').notNull().references(()=>users.id),...timestamps},(t)=>[uniqueIndex('uq_project_material_reference').on(t.projectId,t.reference),index('idx_project_material_status').on(t.projectId,t.status)]);
export const projectVariations=sqliteTable('project_variations',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),number:text('number').notNull(),title:text('title').notNull(),description:text('description').notNull(),reason:text('reason').notNull(),requestedByParty:text('requested_by_party'),affectedScope:text('affected_scope'),originalValueMinor:text('original_value_minor').notNull().default('0'),costImpactMinor:text('cost_impact_minor').notNull().default('0'),revisedValueMinor:text('revised_value_minor').notNull().default('0'),timeImpactDays:integer('time_impact_days').notNull().default(0),submittedAt:integer('submitted_at',{mode:'timestamp_ms'}),decisionRequiredAt:integer('decision_required_at',{mode:'timestamp_ms'}),status:text('status').notNull().default('draft'),approvedValueMinor:text('approved_value_minor'),approvedExtensionDays:integer('approved_extension_days'),detailsJson:text('details_json'),supportingDocumentId:text('supporting_document_id').references(()=>documents.id),createdBy:text('created_by').notNull().references(()=>users.id),...timestamps},(t)=>[uniqueIndex('uq_project_variation_number').on(t.projectId,t.number)]);
export const projectRisks=sqliteTable('project_risks',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),title:text('title').notNull(),description:text('description'),category:text('category').notNull(),likelihood:integer('likelihood').notNull(),impact:integer('impact').notNull(),score:integer('score').notNull().default(1),ownerId:text('owner_id').references(()=>users.id),mitigation:text('mitigation').notNull(),contingency:text('contingency'),targetAt:integer('target_at',{mode:'timestamp_ms'}),status:text('status').notNull().default('open'),detailsJson:text('details_json'),...timestamps},(t)=>[index('idx_project_risk_status').on(t.projectId,t.status)]);
export const projectIssues=sqliteTable('project_issues',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),title:text('title').notNull(),description:text('description').notNull(),category:text('category'),priority:text('priority').notNull().default('normal'),ownerId:text('owner_id').references(()=>users.id),raisedBy:text('raised_by').notNull().references(()=>users.id),raisedAt:integer('raised_at',{mode:'timestamp_ms'}).notNull(),targetResolutionAt:integer('target_resolution_at',{mode:'timestamp_ms'}),scheduleImpact:text('schedule_impact'),costImpactMinor:text('cost_impact_minor').notNull().default('0'),immediateAction:text('immediate_action'),detailsJson:text('details_json'),status:text('status').notNull().default('open'),resolution:text('resolution'),...timestamps},(t)=>[index('idx_project_issue_status').on(t.projectId,t.status)]);
export const projectIncidents=sqliteTable('project_incidents',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),occurredAt:integer('occurred_at',{mode:'timestamp_ms'}).notNull(),location:text('location').notNull(),type:text('type').notNull(),description:text('description').notNull(),peopleInvolved:text('people_involved'),immediateAction:text('immediate_action').notNull(),severity:text('severity').notNull(),followUp:text('follow_up'),status:text('status').notNull().default('open'),reportedBy:text('reported_by').notNull().references(()=>users.id),...timestamps},(t)=>[index('idx_project_incident_date').on(t.projectId,t.occurredAt)]);
export const projectActivities=sqliteTable('project_activities',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),actorId:text('actor_id').references(()=>users.id),action:text('action').notNull(),summary:text('summary').notNull(),entityType:text('entity_type'),entityId:text('entity_id'),occurredAt:integer('occurred_at',{mode:'timestamp_ms'}).notNull()},(t)=>[index('idx_project_activity_date').on(t.projectId,t.occurredAt)]);
export const projectMaterialUsage=sqliteTable('project_material_usage',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),material:text('material').notNull(),quantityIssuedMinor:text('quantity_issued_minor').notNull(),quantityUsedMinor:text('quantity_used_minor').notNull(),quantityReturnedMinor:text('quantity_returned_minor').notNull(),occurredAt:integer('occurred_at',{mode:'timestamp_ms'}).notNull(),activity:text('activity').notNull(),issuedBy:text('issued_by').notNull(),receivedBy:text('received_by').notNull(),notes:text('notes'),createdBy:text('created_by').notNull().references(()=>users.id),...timestamps},(t)=>[index('idx_project_material_usage_date').on(t.projectId,t.occurredAt)]);
export const projectLabourRecords=sqliteTable('project_labour_records',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),occurredAt:integer('occurred_at',{mode:'timestamp_ms'}).notNull(),workerTeam:text('worker_team').notNull(),workerType:text('worker_type').notNull(),tradeRole:text('trade_role').notNull(),activity:text('activity').notNull(),regularHoursMinor:text('regular_hours_minor').notNull(),overtimeHoursMinor:text('overtime_hours_minor').notNull().default('0'),workCompleted:text('work_completed').notNull(),rateMinor:text('rate_minor').notNull().default('0'),supervisor:text('supervisor').notNull(),notes:text('notes'),createdBy:text('created_by').notNull().references(()=>users.id),...timestamps},(t)=>[index('idx_project_labour_date').on(t.projectId,t.occurredAt)]);
export const projectEquipmentRecords=sqliteTable('project_equipment_records',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),equipment:text('equipment').notNull(),equipmentCode:text('equipment_code').notNull(),type:text('type').notNull(),source:text('source').notNull(),assignedAt:integer('assigned_at',{mode:'timestamp_ms'}).notNull(),expectedReturnAt:integer('expected_return_at',{mode:'timestamp_ms'}),operator:text('operator').notNull(),activity:text('activity').notNull(),hoursUsedMinor:text('hours_used_minor').notNull().default('0'),fuelNotes:text('fuel_notes'),condition:text('condition').notNull(),maintenanceIssue:integer('maintenance_issue',{mode:'boolean'}).notNull().default(false),status:text('status').notNull().default('assigned'),notes:text('notes'),createdBy:text('created_by').notNull().references(()=>users.id),...timestamps},(t)=>[index('idx_project_equipment_status').on(t.projectId,t.status)]);
export const projectCertificates=sqliteTable('project_certificates',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),certificateType:text('certificate_type').notNull(),number:text('number').notNull(),period:text('period').notNull(),relatedMilestone:text('related_milestone'),submittedAt:integer('submitted_at',{mode:'timestamp_ms'}).notNull(),submittedValueMinor:text('submitted_value_minor').notNull().default('0'),certifiedValueMinor:text('certified_value_minor').notNull().default('0'),approvedAt:integer('approved_at',{mode:'timestamp_ms'}),approvedBy:text('approved_by'),documentId:text('document_id').references(()=>documents.id),notes:text('notes'),status:text('status').notNull().default('submitted'),...timestamps},(t)=>[uniqueIndex('uq_project_certificate_number').on(t.projectId,t.number)]);
export const projectDocumentLinks=sqliteTable('project_document_links',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),documentId:text('document_id').notNull().references(()=>documents.id),category:text('category').notNull(),title:text('title').notNull(),referenceNumber:text('reference_number'),version:text('version').notNull(),documentAt:integer('document_at',{mode:'timestamp_ms'}).notNull(),expiresAt:integer('expires_at',{mode:'timestamp_ms'}),stage:text('stage'),relatedMilestone:text('related_milestone'),notes:text('notes'),...timestamps},(t)=>[index('idx_project_documents_category').on(t.projectId,t.category)]);
export const projectInvoiceDetails=sqliteTable('project_invoice_details',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),invoiceId:text('invoice_id').notNull().references(()=>invoices.id),certificateReference:text('certificate_reference'),description:text('description').notNull(),paymentInstructions:text('payment_instructions').notNull(),supportingDocumentId:text('supporting_document_id').references(()=>documents.id),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[uniqueIndex('uq_project_invoice_detail').on(t.invoiceId)]);
export const projectPaymentDetails=sqliteTable('project_payment_details',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),paymentId:text('payment_id').notNull().references(()=>payments.id),invoiceId:text('invoice_id').references(()=>invoices.id),paymentType:text('payment_type').notNull(),bankAccount:text('bank_account').notNull(),allocation:text('allocation').notNull(),notes:text('notes'),receiptDocumentId:text('receipt_document_id').references(()=>documents.id),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull()},(t)=>[uniqueIndex('uq_project_payment_detail').on(t.paymentId)]);
export const projectRetentionDetails=sqliteTable('project_retention_details',{id:id(),projectId:text('project_id').notNull().references(()=>projects.id),retentionId:text('retention_id').notNull().references(()=>retentions.id),applicable:integer('applicable',{mode:'boolean'}).notNull().default(true),defectsStartAt:integer('defects_start_at',{mode:'timestamp_ms'}),defectsEndAt:integer('defects_end_at',{mode:'timestamp_ms'}),requestAt:integer('request_at',{mode:'timestamp_ms'}),notes:text('notes'),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull()},(t)=>[uniqueIndex('uq_project_retention_detail').on(t.retentionId)]);
export const procurementRequestItems = sqliteTable('procurement_request_items', { id: id(), requestId: text('request_id').notNull().references(() => procurementRequests.id), description: text('description').notNull(), quantityMinor: text('quantity_minor').notNull(), unit: text('unit').notNull(), estimatedUnitCostMinor: text('estimated_unit_cost_minor'), sequence: integer('sequence').notNull() }, (t) => [index('idx_procurement_request_items_request').on(t.requestId)]);
export const rfqs = sqliteTable('rfqs', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), reference: text('reference').notNull(), requestId: text('request_id').notNull().references(() => procurementRequests.id), issuedAt: integer('issued_at', { mode: 'timestamp_ms' }), closesAt: integer('closes_at', { mode: 'timestamp_ms' }).notNull(), status: text('status').notNull().default('draft'), ...timestamps }, (t) => [uniqueIndex('uq_rfqs_company_reference').on(t.companyId, t.reference)]);
export const supplierQuotations = sqliteTable('supplier_quotations', { id: id(), rfqId: text('rfq_id').notNull().references(() => rfqs.id), supplierId: text('supplier_id').notNull().references(() => suppliers.id), reference: text('reference'), currency: text('currency').notNull().default('UGX'), subtotalMinor: text('subtotal_minor').notNull(), taxMinor: text('tax_minor').notNull().default('0'), totalMinor: text('total_minor').notNull(), leadTimeDays: integer('lead_time_days'), selected: integer('selected', { mode: 'boolean' }).notNull().default(false), ...timestamps }, (t) => [uniqueIndex('uq_supplier_quotation').on(t.rfqId, t.supplierId)]);
export const purchaseOrderItems = sqliteTable('purchase_order_items', { id: id(), purchaseOrderId: text('purchase_order_id').notNull().references(() => purchaseOrders.id), inventoryItemId: text('inventory_item_id').references(() => inventoryItems.id), description: text('description').notNull(), quantityMinor: text('quantity_minor').notNull(), unit: text('unit').notNull(), unitCostMinor: text('unit_cost_minor').notNull(), lineTotalMinor: text('line_total_minor').notNull(), sequence: integer('sequence').notNull() }, (t) => [index('idx_purchase_order_items_order').on(t.purchaseOrderId)]);
export const goodsReceiptItems = sqliteTable('goods_receipt_items', { id: id(), goodsReceiptId: text('goods_receipt_id').notNull().references(() => goodsReceipts.id), purchaseOrderItemId: text('purchase_order_item_id').notNull().references(() => purchaseOrderItems.id), receivedQuantityMinor: text('received_quantity_minor').notNull(), acceptedQuantityMinor: text('accepted_quantity_minor').notNull(), rejectedQuantityMinor: text('rejected_quantity_minor').notNull().default('0'), notes: text('notes') }, (t) => [index('idx_goods_receipt_items_receipt').on(t.goodsReceiptId)]);
export const inventoryBatches = sqliteTable('inventory_batches', { id: id(), itemId: text('item_id').notNull().references(() => inventoryItems.id), warehouseId: text('warehouse_id').notNull().references(() => warehouses.id), batchNumber: text('batch_number').notNull(), serialNumber: text('serial_number'), manufacturer: text('manufacturer'), expiresAt: integer('expires_at', { mode: 'timestamp_ms' }), quantityMinor: text('quantity_minor').notNull(), ...timestamps }, (t) => [uniqueIndex('uq_inventory_batch').on(t.itemId, t.warehouseId, t.batchNumber), index('idx_inventory_batches_expiry').on(t.expiresAt)]);
export const creditNotes = sqliteTable('credit_notes', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), number: text('number').notNull(), invoiceId: text('invoice_id').notNull().references(() => invoices.id), currency: text('currency').notNull().default('UGX'), amountMinor: text('amount_minor').notNull(), reason: text('reason').notNull(), status: text('status').notNull().default('draft'), journalEntryId: text('journal_entry_id').references(() => journalEntries.id), ...timestamps }, (t) => [uniqueIndex('uq_credit_notes_company_number').on(t.companyId, t.number)]);
export const cheques = sqliteTable('cheques', { id: id(), bankAccountId: text('bank_account_id').notNull().references(() => bankAccounts.id), chequeNumber: text('cheque_number').notNull(), payee: text('payee').notNull(), currency: text('currency').notNull().default('UGX'), amountMinor: text('amount_minor').notNull(), chequeDate: integer('cheque_date', { mode: 'timestamp_ms' }).notNull(), purpose: text('purpose').notNull(), supplierId: text('supplier_id').references(() => suppliers.id), projectId: text('project_id').references(() => projects.id), approvalRequestId: text('approval_request_id').references(() => approvalRequests.id), status: text('status').notNull().default('prepared'), ...timestamps }, (t) => [uniqueIndex('uq_cheque_number_account').on(t.bankAccountId, t.chequeNumber)]);
export const payrollEntries = sqliteTable('payroll_entries', { id: id(), payrollRunId: text('payroll_run_id').notNull().references(() => payrollRuns.id), employeeId: text('employee_id').notNull().references(() => employees.id), grossMinor: text('gross_minor').notNull(), deductionsMinor: text('deductions_minor').notNull(), netMinor: text('net_minor').notNull(), status: text('status').notNull().default('calculated') }, (t) => [uniqueIndex('uq_payroll_entry_employee').on(t.payrollRunId, t.employeeId)]);
export const payrollComponents = sqliteTable('payroll_components', { id: id(), payrollEntryId: text('payroll_entry_id').notNull().references(() => payrollEntries.id), code: text('code').notNull(), name: text('name').notNull(), type: text('type').notNull(), amountMinor: text('amount_minor').notNull(), ruleVersion: text('rule_version') }, (t) => [index('idx_payroll_components_entry').on(t.payrollEntryId)]);
export const taxRules = sqliteTable('tax_rules', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), name: text('name').notNull(), code: text('code').notNull(), basisPoints: integer('basis_points').notNull(), effectiveAt: integer('effective_at', { mode: 'timestamp_ms' }).notNull(), applicability: text('applicability').notNull(), inclusive: integer('inclusive', { mode: 'boolean' }).notNull().default(false), active: integer('active', { mode: 'boolean' }).notNull().default(true), configurationJson: text('configuration_json'), ...timestamps }, (t) => [uniqueIndex('uq_tax_rules_version').on(t.companyId, t.code, t.effectiveAt)]);
export const calendarEvents = sqliteTable('calendar_events', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), title: text('title').notNull(), category: text('category').notNull(), startsAt: integer('starts_at', { mode: 'timestamp_ms' }).notNull(), endsAt: integer('ends_at', { mode: 'timestamp_ms' }), entityType: text('entity_type'), entityId: text('entity_id'), ownerId: text('owner_id').references(() => users.id), status: text('status').notNull().default('scheduled'), ...timestamps }, (t) => [index('idx_calendar_events_company_start').on(t.companyId, t.startsAt)]);
export const emailTemplates = sqliteTable('email_templates', { id: id(), companyId: text('company_id').notNull().references(() => companies.id), code: text('code').notNull(), subject: text('subject').notNull(), htmlBody: text('html_body').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex('uq_email_templates_company_code').on(t.companyId, t.code)]);
