-- Production V1 intentionally contains no business demo seed data.
-- Database structure and authorization baselines are created by drizzle migrations.
-- Real company master data is imported through scripts/import-quickbooks-master.mjs.
-- Real user accounts are provisioned through scripts/create-production-admin.mjs
-- and the production administration workflow.
