'use client';
import Link from 'next/link';
import { ArrowLeft, Download, Mail, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { StarAfricaLogo } from '@/components/star-africa-logo';
type Data = {
  statement: Record<string, unknown>;
  lines: Array<Record<string, unknown>>;
  aging: Record<string, string>;
};
const s = (v: unknown) =>
  typeof v === 'string'
    ? v
    : v == null
      ? ''
      : typeof v === 'number' || typeof v === 'bigint' || typeof v === 'boolean'
        ? String(v)
        : JSON.stringify(v);
const n = (v: unknown) => Number(v ?? 0);
const money = (v: unknown, c: string) =>
  `${c} ${(n(v) / 100).toLocaleString('en-UG', { minimumFractionDigits: 2 })}`;
const date = (v: unknown) =>
  new Date(n(v)).toLocaleDateString('en-UG', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
export function CustomerStatement({ data }: { data: Data }) {
  const st = data.statement;
  const email = () =>
    alert(
      'Email provider not configured. Download or print the statement instead.',
    );
  return (
    <main className="statement-page">
      <nav>
        <Button
          variant="outline"
          render={<Link href={`/customers/${s(st.customer_id)}`} />}
        >
          <ArrowLeft />
          Customer
        </Button>
        <div>
          <Button variant="outline" onClick={email}>
            <Mail />
            Email statement
          </Button>
          <Button variant="outline" onClick={() => window.print()}>
            <Download />
            Export PDF
          </Button>
          <Button onClick={() => window.print()}>
            <Printer />
            Print
          </Button>
        </div>
      </nav>
      <article className="statement-sheet">
        <header>
          <StarAfricaLogo size="large" />
          <div>
            <p>STAR AFRICA OS</p>
            <h1>Customer statement</h1>
            <strong>{s(st.statement_number)}</strong>
          </div>
        </header>
        <section className="statement-address">
          <div>
            <span>Statement for</span>
            <strong>{s(st.customer_name)}</strong>
            <p>
              {s(st.customer_code)}
              {st.tin ? ` · TIN ${s(st.tin)}` : ''}
              <br />
              {s(st.address)}
            </p>
          </div>
          <dl>
            <div>
              <dt>Period</dt>
              <dd>
                {date(st.period_from)} — {date(st.period_to)}
              </dd>
            </div>
            <div>
              <dt>Currency</dt>
              <dd>{s(st.currency)}</dd>
            </div>
            <div>
              <dt>Generated</dt>
              <dd>{date(st.generated_at)}</dd>
            </div>
            <div>
              <dt>Generated by</dt>
              <dd>{s(st.generated_by_name)}</dd>
            </div>
          </dl>
        </section>
        <div className="statement-opening">
          <span>Opening balance</span>
          <strong>{money(st.opening_balance_minor, s(st.currency))}</strong>
        </div>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Reference</th>
              <th>Description</th>
              <th>Debit</th>
              <th>Credit</th>
              <th>Balance</th>
            </tr>
          </thead>
          <tbody>
            {data.lines.length ? (
              data.lines.map((r) => (
                <tr key={s(r.id)}>
                  <td>{date(r.occurred_at)}</td>
                  <td>{s(r.reference)}</td>
                  <td>{s(r.description)}</td>
                  <td>
                    {n(r.debit_minor)
                      ? money(r.debit_minor, s(st.currency))
                      : '—'}
                  </td>
                  <td>
                    {n(r.credit_minor)
                      ? money(r.credit_minor, s(st.currency))
                      : '—'}
                  </td>
                  <td>{money(r.balance_minor, s(st.currency))}</td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={6}>No transactions in this period.</td>
              </tr>
            )}
          </tbody>
        </table>
        <section className="aging">
          <h2>Receivables aging</h2>
          <div>
            {[
              ['current', 'Current'],
              ['days30', '1–30 days'],
              ['days60', '31–60 days'],
              ['days90', '61–90 days'],
              ['over90', '90+ days'],
            ].map(([k, l]) => (
              <article key={k}>
                <span>{l}</span>
                <strong>{money(data.aging[k], s(st.currency))}</strong>
              </article>
            ))}
          </div>
        </section>
        <section className="statement-totals">
          <div>
            <span>Current balance</span>
            <strong>{money(st.closing_balance_minor, s(st.currency))}</strong>
          </div>
          <div>
            <span>Overdue balance</span>
            <strong>{money(st.overdue_balance_minor, s(st.currency))}</strong>
          </div>
          <div>
            <span>Retention outstanding</span>
            <strong>
              {money(st.retention_outstanding_minor, s(st.currency))}
            </strong>
          </div>
        </section>
        <footer>
          This statement is generated from Star Africa’s authoritative invoice
          and payment records.
        </footer>
      </article>
    </main>
  );
}
