import { NextResponse } from 'next/server';
import { eq } from 'drizzle-orm';
import { getSession } from '@/lib/security/session';
import { hasPermission } from '@/lib/security/permissions';
import { getDb } from '@/db';
import { auditLogs, bidActivities, bidApprovals, bidResults, bidSubmissions, bids } from '@/db/schema';
import { demoBids } from '@/lib/bids/demo-data';

const actionPermission:Record<string,string>={approve_pursuit:'bids.approve',final_approval:'bids.approve',submit:'bids.submit',record_result:'bids.award'};

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}) {
  const session=await getSession(); if(!session)return NextResponse.json({error:'Authentication required.'},{status:401}); const {id}=await params; const body=await request.json().catch(()=>null) as {type?:string;result?:string}|null; const type=body?.type??''; const permission=actionPermission[type]; if(!permission)return NextResponse.json({error:'Unsupported bid action.'},{status:400}); if(!hasPermission(session.permissions,permission))return NextResponse.json({error:'You do not have permission to perform this action.'},{status:403});
  const demo=demoBids.find((bid)=>bid.id===id); let nextStatus:string|undefined; let message='Action recorded.'; if(type==='approve_pursuit'){if(demo&&demo.stage!=='qualification')return NextResponse.json({error:'Pursuit approval is only valid during Qualification.'},{status:409});nextStatus='approved_to_pursue';message='Pursuit approval recorded. The bid can now enter preparation.';} if(type==='final_approval'){message='Final submission approval recorded with approver and timestamp.';} if(type==='submit'){return NextResponse.json({error:'Submission is blocked: mandatory requirements and final approval are outstanding.'},{status:409});} if(type==='record_result'){if(!['won','lost'].includes(body?.result??''))return NextResponse.json({error:'Result must be won or lost.'},{status:400});if(demo&&demo.stage!=='awaiting_result')return NextResponse.json({error:'A result can only be recorded while awaiting result.'},{status:409});nextStatus=body!.result;message=`Bid result recorded as ${body!.result!.toUpperCase()}.`;}
  const now=new Date(); const db=getDb(); const statements=[]; if(nextStatus)statements.push(db.update(bids).set({status:nextStatus,updatedAt:now}).where(eq(bids.id,id))); if(type==='final_approval')statements.push(db.insert(bidApprovals).values({id:`approval-${crypto.randomUUID()}`,bidId:id,type:'final_submission',approverId:session.userId,decision:'approved',comments:'Approved in demonstration workflow.',decidedAt:now,createdAt:now})); if(type==='record_result')statements.push(db.insert(bidResults).values({id:`result-${crypto.randomUUID()}`,bidId:id,result:body!.result!,decisionDate:now,currency:'UGX',recordedBy:session.userId,createdAt:now,updatedAt:now})); if(type==='submit')statements.push(db.insert(bidSubmissions).values({id:`submission-${crypto.randomUUID()}`,bidId:id,method:'portal',submittedAt:now,submittedBy:session.userId,packageManifestJson:'[]',status:'submitted',createdAt:now})); statements.push(db.insert(bidActivities).values({id:`activity-${crypto.randomUUID()}`,bidId:id,actorId:session.userId,action:`bid.${type}`,linkedEntityType:'bid',linkedEntityId:id,summary:message,occurredAt:now})); statements.push(db.insert(auditLogs).values({id:`audit-${crypto.randomUUID()}`,companyId:'company-star-africa',userId:session.userId,action:`bid.${type}`,entityType:'bid',entityId:id,newValueJson:JSON.stringify(body),occurredAt:now}));
  try{await db.batch(statements as [typeof statements[number],...typeof statements[number][]]);}catch(error){if(!demo)return NextResponse.json({error:error instanceof Error?error.message:'Unable to record action.'},{status:503});}
  return NextResponse.json({message,status:nextStatus});
}
